var _ = require('lodash');

var mutationTableIndex = [
	{name: 'Body: Form', range: _.range(1, 201)},
	{name: 'Body: Function', range: _.range(201, 401)},
	{name: 'Mind: Behaviours', range: _.range(401, 501)},
	{name: 'Mind: Cognition', range: _.range(501, 601)},
	{name: 'Psychic Powers', range: _.range(601, 701)},
	{name: 'Supernatural Attributes', range: _.range(701, 1001)}	
];

var bodyForm = [
	{name: "Wrinkled Skin", range: [200]},
	{name: "Strange Ears", range: [150]},
	{name: "Wings", range: [195, 196, 197, 198, 199]},
	{name: "Stomach Orifice", range: [149]},
	{name: "Wide", range: [194]},
	{name: "Snout", range: [148]},
	{name: "Whiskers", range: [192, 193]},
	{name: "Small Size", range: [144, 145, 146, 147]},
	{name: "Webbed Digits", range: [189, 190, 191]},
	{name: "Skull Face", range: [143]},
	{name: "Weapon Hands", range: [188]},
	{name: "Siamese Twin", range: [142]},
	{name: "Warty Skin", range: [187]},
	{name: "Short Legs", range: [141]},
	{name: "Walking Head", range: [186]},
	{name: "Scars", range: [140]},
	{name: "Vestigial Wings", range: [185]},
	{name: "Scales", range: [137, 138, 139]},
	{name: "Twisted Frame", range: [184]},
	{name: "Reverse Pedalism", range: [134, 135, 136]},
	{name: "Tumours", range: [182, 183]},
	{name: "Redundant Vital Organs", range: [133]},
	{name: "Trunk", range: [181]},
	{name: "Re-Arranged Face", range: [132]},
	{name: "Transparent Eyelids", range: [178, 179, 180]},
	{name: "Radula", range: [131]},
	{name: "Toothed Skin", range: [177]},
	{name: "Quills, Spines, or Thorns", range: [130]},
	{name: "Tongueless", range: [176]},
	{name: "Puny", range: [129]},
	{name: "Tentacles", range: [174, 175]},
	{name: "Protective Eyelids", range: [128]},
	{name: "Taller", range: [173]},
	{name: "Pouch", range: [127]},
	{name: "Tail", range: [168, 159, 170, 171, 172]},
	{name: "Pointed Head", range: [125, 126]},
	{name: "Sympathetic Biomorphism", range: [167]},
	{name: "Pinhead", range: [124]},
	{name: "Stubby Digits", range: [166]},
	{name: "Physically Immature", range: [123]},
	{name: "Strangely-Coloured Skin", range: [161, 162, 163, 164, 165]},
	{name: "Patterned Skin", range: [118,119, 120, 121, 122]},
	{name: "Strangely-Coloured Hair", range: [157, 158, 159, 160]},
	{name: "Overgrown Body Part", range: [117]},
	{name: "Strangely-Coloured Eyes", range: [153, 154, 155, 156]},
	{name: "One Eye", range: [116]},
	{name: "Strange Texture", range: [152]},
	{name: "Oddly-Shaped Tongue", range: [114, 115]},
	{name: "Strange Interior Organs", range: [151]},
	{name: "No Skin", range: [113]},
	{name: "No Nose", range: [112]},
	{name: "Fangs", range: [57, 58, 59, 60]},
	{name: "No Eyes", range: [111]},
	{name: "Eyestalks", range: [56]},
	{name: "No Ears", range: [110]},
	{name: "Extremely Thin", range: [54, 55]},
	{name: "Multiple Legs", range: [109]},
	{name: "Extra Orifices", range: [53]},
	{name: "Multiple Heads", range: [108]},
	{name: "Extra Joints", range: [52]},
	{name: "Multiple Arms", range: [107]},
	{name: "Extra Fingers and Toes", range: [50, 51]},
	{name: "Mostly Hairless", range: [106]},
	{name: "Extra Eyes", range: [48, 49]},
	{name: "Mane", range: [105]},
	{name: "Exotic Genitalia", range: [46, 47]},
	{name: "Loose Skin", range: [104]},
	{name: "Enormously Fat", range: [44, 45]},
	{name: "Long Tongue", range: [103]},
	{name: "Double Mouth", range: [43]},
	{name: "Nose", range: [102]},
	{name: "Doppelgänger", range: [42]},
	{name: "Long Neck", range: [101]},
	{name: "Diffused Organs", range: [41]},
	{name: "Long Legs", range: [100]},
	{name: "Crown", range: [40]},
	{name: "Long Face", range: [99]},
	{name: "Crest", range: [38, 39]},
	{name: "Limb Transference", range: [98]},
	{name: "Covered in Orifices", range: [37]},
	{name: "Limb Loss", range: [97]},
	{name: "Complex Mouthparts", range: [36]},
	{name: "Leaves", range: [96]},
	{name: "Clubfoot", range: [34, 35]},
	{name: "Large Size", range: [92, 93, 94, 95]},
	{name: "Clothes", range: [33]},
	{name: "Large Rear End", range: [91]},
	{name: "Claws", range: [29, 30, 31, 32]},
	{name: "Large Ears", range: [89, 90]},
	{name: "Cilia", range: [28]},
	{name: "Internal Weapon", range: [88]},
	{name: "Changing Colours", range: [27]},
	{name: "Hunchback", range: [87]},
	{name: "Cat's Eyes", range: [25, 26]},
	{name: "Hump", range: [86]},
	{name: "Bulging Eyes", range: [24]},
	{name: "Hideous Appearance", range: [85]},
	{name: "Bristles", range: [23]},
	{name: "Huge Head", range: [83, 84]},
	{name: "Boils and Sores", range: [22]},
	{name: "Huge Beard", range: [82]},
	{name: "Body Barbs", range: [21]},
	{name: "Horns", range: [79, 80, 81]},
	{name: "Birthmark", range: [20]},
	{name: "Hopper", range: [78]},
	{name: "Bestial Face", range: [19]},
	{name: "Hooks", range: [77]},
	{name: "Beak", range: [18]},
	{name: "Hemihypertrophy", range: [76]},
	{name: "Backwards Parts", range: [17]},
	{name: "Headless", range: [75]},
	{name: "Attractive", range: [14, 15, 16]},
	{name: "Hairless", range: [73, 74]},
	{name: "Atrophied or Malformed Part", range: [13]},
	{name: "Gliding Membranes", range: [72]},
	{name: "Armour", range: [10, 11, 12]},
	{name: "FusedRibs", range: [71]},
	{name: "Anthropomorphic Animal", range: [8, 9]},
	{name: "Fur", range: [66, 67, 68, 69, 70]},
	{name: "Antennae", range: [6, 7]},
	{name: "Flippers", range: [65]},
	{name: "Animal Feet", range: [5]},
	{name: "Flaking Skin", range: [64]},
	{name: "Amorphous", range: [4]},
	{name: "Fin", range: [63]},
	{name: "Alternate Locomotion", range: [3]},
	{name: "Feathers", range: [61, 62]},
	{name: "Albino", range: [1, 2]}	
].reverse();

var bodyFunctions = [
	{range: [201, 202], name: "Adhesive Touch"},
	{range: [219], name: "Cocoon"},
	{range: [203, 204], name: "Allergies"},
	{range: [220, 221], name: "Cold Blooded"},
	{range: [205, 206], name: "Ambidextrous"},
	{range: [222, 223], name: "Colour Blind"},
	{range: [207], name: "Anaerobic"},
	{range: [224], name: "Cracking Joints"},
	{range: [208], name: "Aquatic Adaptation"},
	{range: [225], name: "Deaf"},
	{range: [209], name: "Bad Breath"},
	{range: [226, 227], name: "Decreased Metabolism"},
	{range: [210, 211, 212], name: "Bioluminescent"},
	{range: [228, 229, 230, 231, 232], name: "Decreased Physical Capability"},
	{range: [213], name: "Blind"},
	{range: [233], name: "Defensive Barbs"},
	{range: [214], name: "Blood Substitution"},
	{range: [234], name: "Diabetes"},
	{range: [215], name: "Buoyancy"},
	{range: [235], name: "Disease Carrier"},
	{range: [216, 217], name: "Chameleoline Skin"},
	{range: [236, 237], name: "Double Jointed"},
	{range: [218], name: "Chronic Pain"},
	{range: [238, 239], name: "Early Maturation"},
	{range: [240], name: "Efficient Digestion"},
	{range: [295], name: "Ink"},
	{range: [241, 242], name: "Electrical Generation"},
	{range: [296], name: "Kidney Stones"},
	{range: [243, 244], name: "Electromagnetic Disruption"},
	{range: [297], name: "Light Dependency"},
	{range: [245], name: "Enhanced Musculature"},
	{range: [298], name: "Light Generation"},
	{range: [246, 247], name: "Enlarging Mouth"},
	{range: [299], name: "Light Sensitivity"},
	{range: [248], name: "Excretion"},
	{range: [300], name: "Long Life"},
	{range: [249], name: "Explosive Death"},
	{range: [301, 302], name: "Low Pain Threshold"},
	{range: [250], name: "Extensible Limbs"},
	{range: [303], name: "Low Sex Drive"},
	{range: [251], name: "Fast Hair Growth"},
	{range: [304, 305], name: "Malformed Mouth"},
	{range: [252], name: "Fragrant"},
	{range: [306], name: "Malleable Body"},
	{range: [253], name: "Frog Tongue"},
	{range: [307], name: "Malleable Features"},
	{range: [254], name: "Fruit"},
	{range: [308], name: "Microscopic Vision"},
	{range: [255], name: "G, Tolerance"},
	{range: [309], name: "Mute"},
	{range: [256], name: "Gas Bag"},
	{range: [310], name: "Myopia"},
	{range: [257], name: "Gas Emission"},
	{range: [311], name: "Nerve Cut, Off"},
	{range: [258, 259], name: "Gills and Lungs"},
	{range: [312], name: "No Pain Receptors"},
	{range: [260], name: "Hangover Resistance"},
	{range: [313], name: "No Sense of Smell or Taste"},
	{range: [261, 262], name: "Heightened Hearing"},
	{range: [314], name: "No Sense of Touch"},
	{range: [263, 264], name: "Heightened Sense of Smell and Taste"},
	{range: [315], name: "Oversexed"},
	{range: [265, 266], name: "Heightened Sense of Touch"},
	{range: [316], name: "Paraplegic"},
	{range: [267, 268], name: "Hemophilia"},
	{range: [317, 318], name: "Parasite Infestation"},
	{range: [269], name: "Hermaphrodite"},
	{range: [319], name: "Parthenogenesis"},
	{range: [270], name: "Hermaphromorph"},
	{range: [320], name: "Performance Enhancement"},
	{range: [271], name: "High Body Temperature"},
	{range: [321], name: "Permeable Skin"},
	{range: [272, 273], name: "High Pain Threshold"},
	{range: [322, 323, 324], name: "Pheromones"},
	{range: [274], name: "Hollow Bones"},
	{range: [325], name: "Photosynthetic"},
	{range: [275], name: "Horrible Stench"},
	{range: [326], name: "Poison Glands"},
	{range: [276], name: "Hyperadrenal Gland"},
	{range: [327], name: "Poison Susceptibility"},
	{range: [277], name: "Hyperopia"},
	{range: [328, 329], name: "Poor Respiration"},
	{range: [278], name: "Immune to Disease"},
	{range: [330], name: "Pouched Cheeks"},
	{range: [279], name: "Immune to Poison"},
	{range: [331], name: "Powerful Jaws"},
	{range: [280], name: "Increased Appendix Size"},
	{range: [332], name: "Powerful Legs"},
	{range: [281], name: "Increased Heart and Lung Size"},
	{range: [333, 334], name: "Prehensile Feet"},
	{range: [282, 283], name: "Increased Metabolism"},
	{range: [335], name: "Prehensile Hair"},
	{range: [284, 285, 286, 287, 288], name: "Increased Physical Capability"},
	{range: [336, 337], name: "Premature Aging"},
	{range: [289], name: "Increased Susceptibility to Illness"},
	{range: [338], name: "Prey Scent"},
	{range: [290], name: "Independently Focusable Eyes"},
	{range: [339], name: "Protected Senses"},
	{range: [291], name: "Infected"},
	{range: [340], name: "Pseudopods"},
	{range: [292], name: "Infertile"},
	{range: [341], name: "Quadriplegic"},
	{range: [293], name: "Inflation"},
	{range: [342], name: "Radar"},
	{range: [294], name: "Infravision"},
	{range: [343], name: "Reflective Skin"},
	{range: [344, 345, 346], name: "Regeneration"},
	{range: [373], name: "Structural Weakness"},
	{range: [347], name: "Respiratory Filters"},
	{range: [374], name: "Suckers"},
	{range: [348], name: "Roots and Vines"},
	{range: [375, 376], name: "Telescopic Vision"},
	{range: [349], name: "Rotating Body Part"},
	{range: [377, 378], name: "Temperature Resistance"},
	{range: [350], name: "Rotting Flesh"},
	{range: [379, 380], name: "Temperature Sensitivity"},
	{range: [351], name: "Rubber Bones"},
	{range: [381], name: "Thin Skin"},
	{range: [352], name: "Rubbery Skin"},
	{range: [382], name: "Total Healing"},
	{range: [353], name: "Saliva Substitution"},
	{range: [383], name: "Toxic"},
	{range: [354], name: "Salt Drinker"},
	{range: [384], name: "Toxin Resistance"},
	{range: [355], name: "Sanitized Metabolism"},
	{range: [385], name: "Trail of Slime"},
	{range: [356], name: "Shapechanger"},
	{range: [386], name: "Tremor Sense"},
	{range: [357], name: "Shedding"},
	{range: [387], name: "Tunnel Vision"},
	{range: [358], name: "Short Life"},
	{range: [388], name: "Ultravision"},
	{range: [359, 360], name: "Silent Movement"},
	{range: [389], name: "Uncontrollable Flatulence"},
	{range: [361], name: "Silk Production"},
	{range: [390, 391], name: "Venomous Bite"},
	{range: [362, 363], name: "Slow Healer"},
	{range: [392], name: "Ventriloquist"},
	{range: [364, 365], name: "Sonar"},
	{range: [393], name: "Vents"},
	{range: [366], name: "Sonic Blast"},
	{range: [394], name: "Voluminous Lungs"},
	{range: [367], name: "Sound Mimicry"},
	{range: [395], name: "Vomits at Will"},
	{range: [368], name: "Spinning"},
	{range: [396], name: "Water Dependency"},
	{range: [369], name: "Spore Cloud"},
	{range: [397], name: "Water, Soluble Skin"},
	{range: [370], name: "Sprint"},
	{range: [398], name: "Weak Spot"},
	{range: [371], name: "Stiff Joints"},
	{range: [399], name: "Wet Skin"},
	{range: [372], name: "Strong Skeleton"},
	{range: [400], name: "Wounding Genitals"}
];

var test = [
	{name: 'Wild', range: _.range(1, 101), subtable: mutationTableIndex},
	{name: 'Boring', range: _.range(101, 201)}
];

//randomly chooses from a table, taking an optional lower limit value other than 1
function pick(table, lowerLimit) {
	var selection = '';
	var lastRange = _.last(table);
	var firstRange = _.first(table);
	var ceiling = _.last(lastRange.range);
	var floor = _.first(firstRange.range);;

	//option to set a floor other than 1
	if (typeof lowerLimit !== 'undefined') {
		floor = lowerLimit;
	}

	var random = _.random(floor, ceiling);
	console.log(random);

	//iterate through table object and checking random number in each range array, returning the key if true
	_.forEach(table, function(data) {
		var start = _.first(data.range);
		var end = _.last(data.range) + 1;
		var bool = _.inRange(random, start, end);

		if (bool == true) {
			selection = data.name;

			if (data.subtable !== undefined) {				
				selection = pick(data.subtable);
			}			
		}		
	});

	return selection;
}

console.log(pick(bodyFunctions));

