var _ = require('lodash');

var otherAnimals = [
	{range: [1], name: "Amoeba"},
	{range: [50], name: "Jumping spider"},
	{range: [2, 3], name: "Ant"},
	{range: [51, 52], name: "Lacewing"},
	{range: [4], name: "Aphid"},
	{range: [53, 54], name: "Ladybird or ladybug"},
	{range: [5], name: "Bark beetle or leaf beetle"},
	{range: [55], name: "Leafhopper or planthopper"},
	{range: [6, 7], name: "Bee or bumblebee"},
	{range: [56], name: "Louse"},
	{range: [8, 9], name: "Bee, killer"},
	{range: [57, 58], name: "Mantis"},
	{range: [10], name: "Beetle"},
	{range: [59], name: "Mayfly"},
	{range: [11], name: "Bush, cricket or katydid"},
	{range: [60, 61], name: "Millipede"},
	{range: [12, 13], name: "Butterfly"},
	{range: [62], name: "Mite"},
	{range: [14], name: "Butterworm or Chilean moth"},
	{range: [63], name: "Mosquito"},
	{range: [15], name: "Caddisfly"},
	{range: [64], name: "Moss piglet or water bear"},
	{range: [16, 17], name: "Caterpillar"},
	{range: [65, 66], name: "Moth"},
	{range: [18], name: "Cave spider"},
	{range: [67], name: "Punctate flower chafer"},
	{range: [19, 20], name: "Centipede"},
	{range: [68, 69], name: "Scarab"},
	{range: [21], name: "Cicada"},
	{range: [70, 71], name: "Scorpion"},
	{range: [22], name: "Cockroach"},
	{range: [72], name: "Scorpionfly"},
	{range: [23], name: "Crane fly"},
	{range: [73], name: "Silkworm"},
	{range: [24, 25], name: "Cricket"},
	{range: [74, 75], name: "Slug"},
	{range: [26], name: "Darkling beetle"},
	{range: [76, 77], name: "Snail"},
	{range: [27, 28], name: "Dragonfly"},
	{range: [78], name: "Snakefly"},
	{range: [29], name: "Dung beetle or ground beetle"},
	{range: [79, 80], name: "Spider"},
	{range: [30], name: "Earwig"},
	{range: [81], name: "Stag beetle"},
	{range: [31, 32], name: "Firefly"},
	{range: [82, 83], name: "Stick bug"},
	{range: [33], name: "Fire ant"},
	{range: [84, 85], name: "Stonefly"},
	{range: [34], name: "Flatworm"},
	{range: [86], name: "Tadpole"},
	{range: [35, 36], name: "Flea"},
	{range: [87], name: "Tarantula"},
	{range: [37], name: "Fluke or tapeworm"},
	{range: [88, 89], name: "Termite"},
	{range: [38], name: "Fly"},
	{range: [90], name: "Thorn bug or treehopper"},
	{range: [39], name: "Froghopper or spittlebug"},
	{range: [91], name: "Tick"},
	{range: [40], name: "Fruitfly"},
	{range: [92], name: "Velvet worm"},
	{range: [41, 42], name: "Grasshopper or locust"},
	{range: [93], name: "Waxworm or wax moth"},
	{range: [43], name: "Grub or maggot"},
	{range: [94], name: "Weevil"},
	{range: [44, 45], name: "Hornet or wasp"},
	{range: [95, 96], name: "Weta"},
	{range: [46], name: "Hoverfly"},
	{range: [97], name: "Whip scorpion"},
	{range: [47, 48], name: "Jewel beetle or jewel bug"},
	{range: [98], name: "Wolf spider"},
	{range: [49], name: "Jumping bristletail"},
	{range: [99, 100], name: "Worm"}
];

var mammals = [
	{range: [1], name: "Aardvark or anteater"},
	{range: [9], name: "Bat"},
	{range: [2], name: "Antelope"},
	{range: [10, 11], name: "Bear"},
	{range: [3], name: "Ape or gorilla"},
	{range: [12], name: "Beaver"},
	{range: [4], name: "Armadillo or pangolin"},
	{range: [13], name: "Bison or buffalo"},
	{range: [5], name: "Auroch"},
	{range: [14], name: "Black, footed cat"},
	{range: [6], name: "Baboon or chimpanzee"},
	{range: [15], name: "Boar"},
	{range: [7], name: "Badger"},
	{range: [16], name: "Bull/cow"},
	{range: [8], name: "Bandicoot"},
	{range: [17], name: "Camel"},
	{range: [18], name: "Caracal or lynx"},
	{range: [60], name: "Monkey"},
	{range: [19], name: "Cat"},
	{range: [61], name: "Moose"},
	{range: [20], name: "Cheetah"},
	{range: [62], name: "Mouse"},
	{range: [21], name: "Chinchilla"},
	{range: [63], name: "Mule"},
	{range: [22], name: "Chipmunk"},
	{range: [64], name: "Muskrat"},
	{range: [23], name: "Cougar, mountain lion, or puma"},
	{range: [65], name: "Naked mole rat"},
	{range: [24], name: "Coyote"},
	{range: [66], name: "Neanderthal"},
	{range: [25], name: "Deer"},
	{range: [67], name: "Opossum or possum"},
	{range: [26, 27], name: "Dog"},
	{range: [68], name: "Orangutan"},
	{range: [28], name: "Donkey"},
	{range: [69], name: "Ox"},
	{range: [29], name: "Elephant"},
	{range: [70], name: "Pig"},
	{range: [30], name: "Elk"},
	{range: [71], name: "Platypus"},
	{range: [31], name: "Ferret"},
	{range: [72], name: "Pony"},
	{range: [32], name: "Fox"},
	{range: [73], name: "Prairie dog"},
	{range: [33], name: "Gazelle"},
	{range: [74], name: "Racoon"},
	{range: [34], name: "Giant panda"},
	{range: [75], name: "Rat"},
	{range: [35], name: "Giraffe"},
	{range: [76], name: "Red panda"},
	{range: [36], name: "Glyptodon"},
	{range: [77], name: "Rhinoceros"},
	{range: [37], name: "Goat"},
	{range: [78], name: "Sabretooth tiger or smilodon"},
	{range: [38], name: "Gopher"},
	{range: [79], name: "Sheep"},
	{range: [39], name: "Guinea pig or hamster"},
	{range: [80], name: "Skunk"},
	{range: [40], name: "Hare or rabbit"},
	{range: [81], name: "Sloth"},
	{range: [41], name: "Hedgehog or porcupine"},
	{range: [82], name: "Slow loris"},
	{range: [42], name: "Hippopotamus"},
	{range: [83], name: "Snow leopard"},
	{range: [43, 44], name: "Horse"},
	{range: [84], name: "Squirrel"},
	{range: [45], name: "Human"},
	{range: [85], name: "Tamarin monkey"},
	{range: [46], name: "Hyena"},
	{range: [86], name: "Tapir"},
	{range: [47], name: "Ibex"},
	{range: [87], name: "Tenrec"},
	{range: [48], name: "Jackal"},
	{range: [88], name: "Tiger"},
	{range: [49], name: "Jaguar, leopard or panther"},
	{range: [89], name: "Warthog"},
	{range: [50], name: "Jerboa"},
	{range: [90], name: "Water buffalo"},
	{range: [51], name: "Kangaroo or wallaby"},
	{range: [91], name: "Weasel"},
	{range: [52], name: "Koala"},
	{range: [92], name: "Wild cat"},
	{range: [53], name: "Lemur"},
	{range: [93], name: "Wildebeest"},
	{range: [54], name: "Lion"},
	{range: [94, 95], name: "Wolf"},
	{range: [55], name: "Mammoth or mastodon"},
	{range: [96], name: "Wolverine"},
	{range: [56], name: "Marmoset"},
	{range: [97], name: "Wombat"},
	{range: [57], name: "Mink"},
	{range: [98], name: "Woolly rat"},
	{range: [58], name: "Mole or shrew"},
	{range: [99], name: "Yak"},
	{range: [59], name: "Mongoose"},
	{range: [100], name: "Zebra"}
];

var plants = [
	{range: [1], name: "Acacia"},
	{range: [40], name: "Corn/Maize or millet"},
	{range: [2], name: "Acanthus or water willow"},
	{range: [41], name: "Cotton or sedge"},
	{range: [3], name: "Aloe"},
	{range: [42], name: "Cypress, juniper, or redwood"},
	{range: [4], name: "Anise, fennel, or liquorice"},
	{range: [43], name: "Dahlia, daisy or sunflower"},
	{range: [5], name: "Apple tree"},
	{range: [44], name: "Damiana or passion flower"},
	{range: [6], name: "Asparagus"},
	{range: [45], name: "Dancing grass or mimosa"},
	{range: [7], name: "Ayahuasca or mimosa"},
	{range: [46], name: "Dandelion"},
	{range: [8], name: "Azalea or rhododendron"},
	{range: [47], name: "Dogbane"},
	{range: [9], name: "Bamboo"},
	{range: [48], name: "Dream herb or leaf of God"},
	{range: [10], name: "Baobab or dragon blood tree"},
	{range: [49], name: "Ebony or persimmon tree"},
	{range: [11], name: "Barley or sorghum"},
	{range: [50], name: "Eggplant or tomato vine"},
	{range: [12], name: "Basil or thyme"},
	{range: [51], name: "Flowering plant"},
	{range: [13], name: "Bean, legume, or pea"},
	{range: [52], name: "Flypaper trap or sundew"},
	{range: [14], name: "Berry or fruit plant"},
	{range: [53], name: "Foxtail"},
	{range: [15], name: "Birch, holly, or oak"},
	{range: [54], name: "Cucumber or zucchini"},
	{range: [16], name: "Bladderwort"},
	{range: [55], name: "Fungus"},
	{range: [17], name: "Blackthorn or coca"},
	{range: [56], name: "Garlic or onion"},
	{range: [18], name: "Boxthorn or nightshade"},
	{range: [57], name: "Goosefoot"},
	{range: [19], name: "Bramble or rose"},
	{range: [58], name: "Gourd, melon, or squash"},
	{range: [20], name: "Broccoli or cauliflower"},
	{range: [59], name: "Grape vine"},
	{range: [21], name: "Bush or fern or shrub"},
	{range: [60], name: "Grass, herb, or weed"},
	{range: [22], name: "Cabbage or lettuce"},
	{range: [61], name: "Green algae"},
	{range: [23], name: "Cacao or Cocoa"},
	{range: [62], name: "Ivy"},
	{range: [24], name: "Cactus"},
	{range: [63], name: "Jasmine"},
	{range: [25], name: "Cane or reed"},
	{range: [64], name: "Kava"},
	{range: [26], name: "Cannabis or Hemp"},
	{range: [65], name: "Kelp or seaweed"},
	{range: [27], name: "Carpet weed or ice plant"},
	{range: [66], name: "Khat or salvia"},
	{range: [28], name: "Carrion flower"},
	{range: [67], name: "Knotweed or smartweed"},
	{range: [29], name: "Carrot, parsnip, radish, or turnip"},
	{range: [68], name: "Laurel"},
	{range: [30], name: "Cedar or pine tree"},
	{range: [69], name: "Lavender, mint, or oregano"},
	{range: [31], name: "Celery, cilantro, or coriander"},
	{range: [70], name: "Lily"},
	{range: [32], name: "Chestnut, lychee, or maple tree"},
	{range: [71], name: "Lotus or poppy"},
	{range: [33], name: "Cholla or peyote"},
	{range: [72], name: "Magnolia or sweetbay"},
	{range: [34], name: "Cinchona"},
	{range: [73], name: "Mandrake"},
	{range: [35], name: "Citrus tree"},
	{range: [74], name: "Mold"},
	{range: [36], name: "Climbing plant or vine"},
	{range: [75], name: "Monkey, puzzle tree"},
	{range: [37], name: "Coffee shrub or tree"},
	{range: [76], name: "Morning glory"},
	{range: [38], name: "Conifer or Evergreen"},
	{range: [77], name: "Moss"},
	{range: [39], name: "Coralillo or Mescal bean"},
	{range: [78], name: "Mushroom or toadstool"},
	{range: [79], name: "Nettle or thistle"},
	{range: [90], name: "Pumpkin"},
	{range: [80], name: "Nutmeg tree"},
	{range: [91], name: "Rice"},
	{range: [81], name: "Oat, rye, or wheat"},
	{range: [92], name: "Root vegetable or tuber"},
	{range: [82], name: "Olive tree"},
	{range: [93], name: "Rubber tree"},
	{range: [83], name: "Onyanga or rose of Jericho"},
	{range: [94], name: "Succulent"},
	{range: [84], name: "Orchid"},
	{range: [95], name: "Sugarcane"},
	{range: [85], name: "Palm tree"},
	{range: [96], name: "Tea"},
	{range: [86], name: "Pepper vine"},
	{range: [97], name: "Terragon or wormwood."},
	{range: [87], name: "Pitcher plant"},
	{range: [98], name: "Tree"},
	{range: [88], name: "Pomegranate tree"},
	{range: [99], name: "Vegetable"},
	{range: [89], name: "Potato or yam"},
	{range: [100], name: "Venus fly trap"}
];

var reptiles = [
	{range: [1], name: "Adder"},
	{range: [36], name: "Draco lizard"},
	{range: [2], name: "Agamid or dragon lizard"},
	{range: [37], name: "Fan, throated lizard"},
	{range: [3, 4], name: "Alligator"},
	{range: [38], name: "Fire, bellied toad"},
	{range: [5], name: "Allosaurus"},
	{range: [39], name: "Frilled lizard"},
	{range: [6], name: "Alpine salamander"},
	{range: [40, 41], name: "Frog"},
	{range: [7], name: "Ankylosaurus"},
	{range: [42, 43], name: "Gecko"},
	{range: [8], name: "Axolotl or mole salamander"},
	{range: [44], name: "Gila monster"},
	{range: [9], name: "Bearded dragon"},
	{range: [45], name: "Glass frog"},
	{range: [10], name: "Blind snake"},
	{range: [46], name: "Glass lizard or glass snake"},
	{range: [11], name: "Boa constrictor"},
	{range: [47], name: "Greaved lizard"},
	{range: [12], name: "Brachiosaurus"},
	{range: [48], name: "Green frog or green toad"},
	{range: [13], name: "Brontosaurus"},
	{range: [49], name: "Hairy frog"},
	{range: [14], name: "Bullfrog"},
	{range: [50], name: "Iguanodon"},
	{range: [15, 16], name: "Caiman"},
	{range: [51], name: "Komodo dragon"},
	{range: [17, 18], name: "Chameleon"},
	{range: [52], name: "Lizard"},
	{range: [19, 20], name: "Chuckwalla or iguana"},
	{range: [53], name: "Marine iguana"},
	{range: [21], name: "Coast horned lizard"},
	{range: [54], name: "Megalosaurus"},
	{range: [22, 23], name: "Cobra"},
	{range: [55], name: "Monitor lizard"},
	{range: [24], name: "Collared lizard"},
	{range: [56, 57], name: "Mudskipper"},
	{range: [25, 26], name: "Common basilisk or Jesus lizard"},
	{range: [58, 59], name: "Newt"},
	{range: [27], name: "Common toad"},
	{range: [60], name: "Oriental garden lizard"},
	{range: [28], name: "Coral snake or milk snake"},
	{range: [61], name: "Pachycephalosaurus"},
	{range: [29, 30], name: "Crocodile"},
	{range: [62], name: "Plated lizard"},
	{range: [31, 32], name: "Desert horned lizard"},
	{range: [63], name: "Pliosaurus"},
	{range: [33], name: "Dimetrodon"},
	{range: [64], name: "Poison dart frog"},
	{range: [34], name: "Dinosaur"},
	{range: [65], name: "Psychoactive toad"},
	{range: [35], name: "Diplodocus"},
	{range: [66], name: "Pterodactyl"},
	{range: [67], name: "Python"},
	{range: [84], name: "Terrapin"},
	{range: [68, 69], name: "Rattlesnake"},
	{range: [85], name: "Thorny devil"},
	{range: [70], name: "Rhinoceros iguana"},
	{range: [86, 87], name: "Toad"},
	{range: [71], name: "Rough, skinned newt"},
	{range: [88, 89], name: "Tortoise or turtle"},
	{range: [72], name: "Sailfin lizard"},
	{range: [90, 91], name: "Tree frog"},
	{range: [73, 74, 75], name: "Salamander"},
	{range: [92], name: "Triceratops"},
	{range: [76], name: "Salamandrid"},
	{range: [93], name: "True toad"},
	{range: [77, 78], name: "Skink"},
	{range: [94, 95], name: "Tuatara"},
	{range: [79], name: "Snake"},
	{range: [96], name: "Tyrannosaurus Rex"},
	{range: [80], name: "Snapping turtle"},
	{range: [97], name: "Velociraptor"},
	{range: [81], name: "Stegosaurus"},
	{range: [98, 99], name: "Viper"},
	{range: [82, 83], name: "Tegu"},
	{range: [100], name: "Water dragon"}
];

var aquatic = [
	{range: [1], name: "Algae"},
	{range: [29], name: "Fathead"},
	{range: [2], name: "Amphipod"},
	{range: [30], name: "Fish"},
	{range: [3], name: "Angelfish or clownfish"},
	{range: [31], name: "Flatworm"},
	{range: [4], name: "Aquatic worm"},
	{range: [32], name: "Flying fish"},
	{range: [5], name: "Armoured snail"},
	{range: [33], name: "Hagfish"},
	{range: [6], name: "Arrow worm"},
	{range: [34], name: "Hatchet fish"},
	{range: [7], name: "Barnacle"},
	{range: [35], name: "Horseshoe crab"},
	{range: [8], name: "Barracuda"},
	{range: [36], name: "Ichthyosaurus"},
	{range: [9], name: "Barreleye fish"},
	{range: [37], name: "Isopod"},
	{range: [10], name: "Beluga whale"},
	{range: [38, 39], name: "Jellyfish"},
	{range: [11], name: "Blowfish"},
	{range: [40], name: "Killer whale"},
	{range: [12], name: "Carp"},
	{range: [41], name: "Kiwa or yeti crab"},
	{range: [13], name: "Catfish"},
	{range: [42], name: "Koi"},
	{range: [14], name: "Clam, mussel, or oyster"},
	{range: [43], name: "Lamprey"},
	{range: [15], name: "Cnidarian"},
	{range: [44], name: "Leafy seadragon"},
	{range: [16], name: "Comb jelly"},
	{range: [45], name: "Leech"},
	{range: [17], name: "Copepod"},
	{range: [46], name: "Lionfish"},
	{range: [18], name: "Coral"},
	{range: [47], name: "Lungfish or walking catfish"},
	{range: [19, 20], name: "Crab"},
	{range: [48], name: "Marine dinosaur"},
	{range: [21, 22], name: "Crayfish or lobster"},
	{range: [49, 50], name: "Mollusc"},
	{range: [23], name: "Cuttlefish"},
	{range: [51], name: "Monkfish"},
	{range: [24], name: "Diving beetle"},
	{range: [52], name: "Napoleon wrasse"},
	{range: [25, 26], name: "Dolphin or porpoise"},
	{range: [53], name: "Narwhal"},
	{range: [27], name: "Double, spine urchin"},
	{range: [54], name: "Nautilus"},
	{range: [28], name: "Eel"},
	{range: [55, 56], name: "Nudibranch"},
	{range: [57, 58], name: "Octopus"},
	{range: [79], name: "Sea urchin"},
	{range: [59], name: "Otter"},
	{range: [80], name: "Seahorse"},
	{range: [60], name: "Parrotfish"},
	{range: [81], name: "Seal"},
	{range: [61], name: "Piranha"},
	{range: [82], name: "Seamoth"},
	{range: [62], name: "Polychaete worm"},
	{range: [83, 84], name: "Shark"},
	{range: [63], name: "Prawn or shrimp"},
	{range: [85], name: "Shellfish"},
	{range: [64], name: "Psychedelic frogfish"},
	{range: [86], name: "Snailfish"},
	{range: [65, 66], name: "Ray"},
	{range: [87], name: "Sponge"},
	{range: [67], name: "Remora"},
	{range: [88, 89], name: "Squid"},
	{range: [68], name: "Salmon or trout"},
	{range: [90], name: "Squidworm"},
	{range: [69], name: "Sardine"},
	{range: [91], name: "Starfish"},
	{range: [70], name: "Sea anemone"},
	{range: [92], name: "Stone fish"},
	{range: [71], name: "Sea cucumber"},
	{range: [93], name: "Sturgeon"},
	{range: [72], name: "Sea lion"},
	{range: [94], name: "Swordfish"},
	{range: [73], name: "Sea nettle"},
	{range: [95], name: "Trilobite"},
	{range: [74], name: "Sea slug"},
	{range: [96], name: "Turbot"},
	{range: [75], name: "Sea snake"},
	{range: [97], name: "Walrus"},
	{range: [76], name: "Sea spider"},
	{range: [98, 99], name: "Whale"},
	{range: [77, 78], name: "Sea turtle"},
	{range: [100], name: "Zebrafish"}
];

var birds = [
	{range: [1, 2], name: "Albatross"},
	{range: [28], name: "Emu"},
	{range: [3], name: "Anthropornis"},
	{range: [29, 30], name: "Falcon"},
	{range: [4], name: "Apteryx or kiwi"},
	{range: [31], name: "Finch"},
	{range: [5], name: "Archaeopteryx"},
	{range: [32], name: "Flamingo"},
	{range: [6], name: "Bee, eater"},
	{range: [33], name: "Goose"},
	{range: [7, 8], name: "Blackbird"},
	{range: [34], name: "Goshawk"},
	{range: [9], name: "Budgie or parakeet"},
	{range: [35], name: "Grouse"},
	{range: [10], name: "Buzzard"},
	{range: [36, 37], name: "Hawk"},
	{range: [11], name: "Cardinal"},
	{range: [38], name: "Heron"},
	{range: [12, 13], name: "Chicken or rooster"},
	{range: [39, 40], name: "Hummingbird"},
	{range: [14], name: "Condor"},
	{range: [41], name: "Ibis"},
	{range: [15], name: "Cormorant"},
	{range: [42, 43], name: "Jay"},
	{range: [16], name: "Crane"},
	{range: [44], name: "Kea"},
	{range: [17, 18], name: "Crow"},
	{range: [45], name: "Kestrel"},
	{range: [19], name: "Cuckoo"},
	{range: [46], name: "Kingfisher"},
	{range: [20], name: "Dodo"},
	{range: [47], name: "Loon"},
	{range: [21, 22], name: "Dove"},
	{range: [48], name: "Macaw"},
	{range: [23, 24, 25], name: "Duck"},
	{range: [49, 50], name: "Magpie"},
	{range: [26, 27], name: "Eagle"},
	{range: [51], name: "Maleo"},
	{range: [52], name: "Oriole"},
	{range: [78, 79], name: "Seagull"},
	{range: [53], name: "Osprey"},
	{range: [80, 81], name: "Shrike"},
	{range: [54], name: "Ostrich or roadrunner"},
	{range: [82, 83], name: "Sparrow"},
	{range: [55, 56, 57, 58], name: "Owl"},
	{range: [84], name: "Sparrowhawk"},
	{range: [59, 60], name: "Parrot"},
	{range: [85, 86], name: "Spoonbill"},
	{range: [61], name: "Partridge"},
	{range: [87], name: "Starling"},
	{range: [62, 63], name: "Peacock"},
	{range: [88], name: "Stork"},
	{range: [64], name: "Pelican or spoonbill"},
	{range: [89], name: "Swallow"},
	{range: [65, 66], name: "Penguin"},
	{range: [90], name: "Swan"},
	{range: [67, 68], name: "Pheasant or quail"},
	{range: [91], name: "Thrush"},
	{range: [69], name: "Pigeon"},
	{range: [92], name: "Toucan"},
	{range: [70], name: "Puffin"},
	{range: [93], name: "Turkey"},
	{range: [71, 72], name: "Quetzal"},
	{range: [94, 95], name: "Vulture"},
	{range: [73, 74], name: "Raven"},
	{range: [96, 97], name: "Wildfowl"},
	{range: [75, 76], name: "Robin"},
	{range: [98, 99], name: "Woodpecker"},
	{range: [77], name: "Rook"},
	{range: [100], name: "Wren"}
];

var fantasticAnimals = [
	{range: [1], name: "Al, mi’raj"},
	{range: [29], name: "Elemental animal"},
	{range: [2], name: "Amphisbaena"},
	{range: [30, 31], name: "Eye Fucker"},
	{range: [3], name: "Androsphynx or Gynosphynx"},
	{range: [32], name: "Fafnir"},
	{range: [4, 5], name: "Bakeneko"},
	{range: [33], name: "Feathered serpent"},
	{range: [6], name: "Basilisk"},
	{range: [34], name: "Fenrir"},
	{range: [7], name: "Behemoth"},
	{range: [35], name: "Flying polyp"},
	{range: [8], name: "Bhole or Dhole"},
	{range: [36, 38], name: "Gargoyle"},
	{range: [9], name: "Brown Jenkin"},
	{range: [39], name: "Ghast"},
	{range: [10], name: "Bugbear"},
	{range: [40, 41], name: "Giant " + pick(otherAnimals)},
	{range: [11], name: "Bunyip"},
	{range: [42, 44], name: "Griffin"},
	{range: [12, 13], name: "Cat from Saturn"},
	{range: [45], name: "Gug"},
	{range: [14], name: "Catoblepas"},
	{range: [46], name: "Helhest"},
	{range: [15], name: "Cerberus"},
	{range: [47], name: "Hellhound"},
	{range: [16, 17, 18], name: "Chimera"},
	{range: [48], name: "Hippalectryon"},
	{range: [19, 20], name: "Cockatrice"},
	{range: [49, 50], name: "Hippocamp"},
	{range: [21], name: "Dahu or wild haggis"},
	{range: [51], name: "Hippogriff"},
	{range: [22], name: "Direwolf"},
	{range: [52], name: "Hoop snake or ouroboros"},
	{range: [23, 24, 25, 26, 27], name: "Dragon"},
	{range: [53], name: "Hound of Tindalos"},
	{range: [28], name: "Drop bear"},
	{range: [54], name: "Human with the head of a " + pick(birds)},
	{range: [55], name: "Hunting Horror"},
	{range: [78, 79], name: "Phoenix"},
	{range: [56, 57, 58], name: "Hydra"},
	{range: [80], name: "Prismatic cloud"},
	{range: [59], name: "Jackalope"},
	{range: [81], name: "Roc"},
	{range: [60], name: "Jaculus"},
	{range: [82], name: "A " + pick(mammals) + " mixed with a " + pick(birds)},
	{range: [61], name: "Kelpie"},
	{range: [83, 84], name: "Salamander"},
	{range: [62, 63], name: "Ki, rin"},
	{range: [85], name: "Shoggoth"},
	{range: [64], name: "Kobold"},
	{range: [86], name: "Simurgh"},
	{range: [65, 66], name: "Kraken"},
	{range: [87], name: "Skvader or wolpertinger"},
	{range: [67], name: "Lamassu or shedu"},
	{range: [88], name: "Sleipnir"},
	{range: [68], name: "Leviathan"},
	{range: [89], name: "Splintercat"},
	{range: [69, 70], name: "Manticore"},
	{range: [90], name: "Tarasque"},
	{range: [71], name: "Nightmare"},
	{range: [91], name: "Thunderbird"},
	{range: [72], name: "Oneirovorous moth"},
	{range: [92, 93], name: "Undead " + pick(mammals)},
	{range: [73], name: "Ophiotaurus"},
	{range: [94, 95, 96], name: "Unicorn"},
	{range: [74], name: "Orb of light"},
	{range: [97], name: "Wyrm"},
	{range: [75], name: "Orthrus"},
	{range: [98], name: "Wyvern"},
	{range: [76], name: "Pegasus"},
	{range: [99], name: "Yeti"},
	{range: [77], name: "Peryton"},
	{range: [100], name: "Zoog"}
];

var fantasticPeoples = [
	{range: [1, 2], name: "Angel"},
	{range: [22], name: "Enchanter or Enchantress"},
	{range: [3], name: "Banshee"},
	{range: [23], name: "Erinys, fury, or nemesis"},
	{range: [4], name: "Beastman"},
	{range: [24], name: "Fairy"},
	{range: [5], name: "Cactoid"},
	{range: [25, 26], name: "Faun or satyr"},
	{range: [6], name: "Centaur"},
	{range: [27], name: "Flesh golem or revenant"},
	{range: [7], name: "Chaos champion"},
	{range: [28], name: "Gharhion"},
	{range: [8], name: "creatures with the head of a " + pick(otherAnimals)},
	{range: [29], name: "Ghost, wraith, or spectre"},
	{range: [9], name: "Cyclops"},
	{range: [30, 31], name: "Ghoul"},
	{range: [10], name: "Dark elf"},
	{range: [32, 33], name: "Giant"},
	{range: [11], name: "Demigod"},
	{range: [34], name: "Gnoll"},
	{range: [12, 13], name: "Demon or devil"},
	{range: [35], name: "Gnome"},
	{range: [14], name: "Djinn or efreet"},
	{range: [36], name: "Goblin"},
	{range: [15], name: "Doppelgänger"},
	{range: [37], name: "Golem"},
	{range: [16], name: "Dryad or nymph"},
	{range: [38, 39], name: "Gorgon or medusa"},
	{range: [17, 18], name: "Dwarf"},
	{range: [40], name: "Green man"},
	{range: [19], name: "Elder thing or great race"},
	{range: [41], name: "Hag or witch"},
	{range: [20, 21], name: "Elf"},
	{range: [42], name: "Halfling"},
	{range: [43], name: "Harpy"},
	{range: [71], name: "Human with a " + pick(plants) + " head"},
	{range: [44], name: "Hero"},
	{range: [72], name: "Pulvi"},
	{range: [45], name: "Hobgoblin"},
	{range: [73], name: "Puppet"},
	{range: [46], name: "Homunculus"},
	{range: [74], name: "Pygmy"},
	{range: [47], name: "Icthyocentaur"},
	{range: [75], name: "Rakshasa"},
	{range: [48], name: "Incubus or succubus"},
	{range: [76], name: "Ratman"},
	{range: [49], name: "Kitsune"},
	{range: [77], name: "A humanoid " + pick(fantasticAnimals) + "/" + pick(fantasticAnimals)},
	{range: [50], name: "Lamia"},
	{range: [78], name: "Saint or bodhisattva"},
	{range: [51], name: "Leprechaun"},
	{range: [79], name: "Sasquatch"},
	{range: [52], name: "Lich"},
	{range: [80], name: "Serpent person"},
	{range: [53], name: "Living shadow"},
	{range: [81], name: "Shereshi"},
	{range: [54], name: "Living statue"},
	{range: [82], name: "Sin eater"},
	{range: [55], name: "Lizardman"},
	{range: [83], name: "Siren"},
	{range: [56], name: "Maenad"},
	{range: [84], name: "Skeleton"},
	{range: [57], name: "Magician"},
	{range: [85], name: "Sorcerer or Sorceress"},
	{range: [58], name: "Merfolk"},
	{range: [86], name: "Sphinx"},
	{range: [59, 60], name: "Minotaur"},
	{range: [87], name: "Sprite"},
	{range: [61], name: "Mummy"},
	{range: [88], name: "Tengu"},
	{range: [62], name: "Naga"},
	{range: [89], name: "Treeman"},
	{range: [63], name: "Nereid or undine"},
	{range: [90, 91], name: "Troll"},
	{range: [64], name: "Nightgaunt"},
	{range: [92], name: "Valkyrie"},
	{range: [65], name: "Offidiyya"},
	{range: [93, 94], name: "Vampire"},
	{range: [66], name: "Ogre"},
	{range: [95], name: "Wendigo"},
	{range: [67], name: "Orc"},
	{range: [96], name: "Were-" + pick(mammals)},
	{range: [68], name: "Pagan god"},
	{range: [97], name: "Werewolf"},
	{range: [69], name: "Penanggalan"},
	{range: [98], name: "Wizard"},
	{range: [70], name: "Pixie"},
	{range: [99, 100], name: "Zombie"}
];

var creatures = [
	{range: [1, 2], name: "Amphibians and Reptiles", subtable: reptiles},
	{range: [9], name: "Other Animals", subtable: otherAnimals},
	{range: [3], name: "Aquatic Animals", subtable: aquatic},
	{range: [10], name: "Plants", subtable: plants},
	{range: [4], name: "Birds", subtable: birds},
	{range: [11], name: "Fantastic Animals", subtable: fantasticAnimals},
	{range: [5, 6, 7, 8], name: "Mammals", subtable: mammals},
	{range: [12], name: "Fantastic Peoples", subtable: fantasticPeoples}
];

var bodyForm = [
	{range: [1, 2], name: "Albino"},
	{range: [61, 62], name: "Feathers"},
	{range: [3], name: "Alternate Locomotion"},
	{range: [63], name: "Fin"},
	{range: [4], name: "Amorphous"},
	{range: [64], name: "Flaking Skin"},
	{range: [5], name: "Animal Feet"},
	{range: [65], name: "Flippers"},
	{range: [6, 7], name: "Antennae"},
	{range: [66, 67, 68, 69, 70], name: "Fur"},
	{range: [8, 9], name: "Anthropomorphic Animal"},
	{range: [71], name: "Fused Ribs"},
	{range: [10, 11, 12], name: "Armour"},
	{range: [72], name: "Gliding Membranes"},
	{range: [13], name: "Atrophied or Malformed Part"},
	{range: [73, 74], name: "Hairless"},
	{range: [14, 15, 16], name: "Attractive"},
	{range: [75], name: "Headless"},
	{range: [17], name: "Backwards Parts"},
	{range: [76], name: "Hemihypertrophy"},
	{range: [18], name: "Beak"},
	{range: [77], name: "Hooks"},
	{range: [19], name: "Bestial Face"},
	{range: [78], name: "Hopper"},
	{range: [20], name: "Birthmark"},
	{range: [79, 80, 81], name: "Horns"},
	{range: [21], name: "Body Barbs"},
	{range: [82], name: "Huge Beard"},
	{range: [22], name: "Boils and Sores"},
	{range: [83, 84], name: "Huge Head"},
	{range: [23], name: "Bristles"},
	{range: [85], name: "Hideous Appearance"},
	{range: [24], name: "Bulging Eyes"},
	{range: [86], name: "Hump"},
	{range: [25, 26], name: "Cat’s Eyes"},
	{range: [87], name: "Hunchback"},
	{range: [27], name: "Changing Colours"},
	{range: [88], name: "Internal Weapon"},
	{range: [28], name: "Cilia"},
	{range: [89, 90], name: "Large Ears"},
	{range: [29, 30, 31, 32], name: "Claws"},
	{range: [91], name: "Large Rear End"},
	{range: [33], name: "Clothes"},
	{range: [92, 93, 94, 95], name: "Large Size"},
	{range: [34, 35], name: "Clubfoot"},
	{range: [96], name: "Leaves"},
	{range: [36], name: "Complex Mouthparts"},
	{range: [97], name: "Limb Loss"},
	{range: [37], name: "Covered in Orifices"},
	{range: [98], name: "Limb Transference"},
	{range: [38, 39], name: "Crest"},
	{range: [99], name: "Long Face"},
	{range: [40], name: "Crown"},
	{range: [100], name: "Long Legs"},
	{range: [41], name: "Diffused Organs"},
	{range: [101], name: "Long Neck"},
	{range: [42], name: "Doppelgänger"},
	{range: [102], name: "Long Nose"},
	{range: [43], name: "Double Mouth"},
	{range: [103], name: "Long Tongue"},
	{range: [44, 45], name: "Enormously Fat"},
	{range: [104], name: "Loose Skin"},
	{range: [46, 47], name: "Exotic Genitalia"},
	{range: [105], name: "Mane"},
	{range: [48, 49], name: "Extra Eyes"},
	{range: [106], name: "Mostly Hairless"},
	{range: [50, 51], name: "Extra Fingers and Toes"},
	{range: [107], name: "Multiple Arms"},
	{range: [52], name: "Extra Joints"},
	{range: [108], name: "Multiple Heads"},
	{range: [53], name: "Extra Orifices"},
	{range: [109], name: "Multiple Legs"},
	{range: [54, 55], name: "Extremely Thin"},
	{range: [110], name: "No Ears"},
	{range: [56], name: "Eyestalks"},
	{range: [111], name: "No Eyes"},
	{range: [57, 58, 59, 60], name: "Fangs"},
	{range: [112], name: "No Nose"},
	{range: [113], name: "No Skin"},
	{range: [151], name: "Strange Interior Organs"},
	{range: [114, 115], name: "Oddly Shaped Tongue"},
	{range: [152], name: "Strange Texture"},
	{range: [116], name: "One Eye"},
	{range: [153, 154, 155, 156], name: "Strangely Coloured Eyes"},
	{range: [117], name: "Overgrown Body Part"},
	{range: [157, 158, 159, 160], name: "Strangely Coloured Hair"},
	{range: [118, 119, 120, 121, 122], name: "Patterned Skin"},
	{range: [161, 162, 163, 164, 165], name: "Strangely Coloured Skin"},
	{range: [123], name: "Physically Immature"},
	{range: [166], name: "Stubby Digits"},
	{range: [124], name: "Pinhead"},
	{range: [167], name: "Sympathetic Biomorphism"},
	{range: [125, 126], name: "Pointed Head"},
	{range: [168, 169, 170, 171, 172], name: "Tail"},
	{range: [127], name: "Pouch"},
	{range: [173], name: "Taller"},
	{range: [128], name: "Protective Eyelids"},
	{range: [174, 175], name: "Tentacles"},
	{range: [129], name: "Puny"},
	{range: [176], name: "Tongueless"},
	{range: [130], name: "Quills, Spines, or Thorns"},
	{range: [177], name: "Toothed Skin"},
	{range: [131], name: "Radula"},
	{range: [178, 179, 180], name: "Transparent Eyelids"},
	{range: [132], name: "Re-Arranged Face"},
	{range: [181], name: "Trunk"},
	{range: [133], name: "Redundant Vital Organs"},
	{range: [182, 183], name: "Tumours"},
	{range: [134, 135, 136], name: "Reverse Pedalism"},
	{range: [184], name: "Twisted Frame"},
	{range: [137, 138, 139], name: "Scales"},
	{range: [185], name: "Vestigial Wings"},
	{range: [140], name: "Scars"},
	{range: [186], name: "Walking Head"},
	{range: [141], name: "Short Legs"},
	{range: [187], name: "Warty Skin"},
	{range: [142], name: "Siamese Twin"},
	{range: [188], name: "Weapon Hands"},
	{range: [143], name: "Skull Face"},
	{range: [189, 190, 191], name: "Webbed Digits"},
	{range: [144, 145, 146, 147], name: "Small Size"},
	{range: [192, 193], name: "Whiskers"},
	{range: [148], name: "Snout"},
	{range: [194], name: "Wide"},
	{range: [149], name: "Stomach Orifice"},
	{range: [195, 196, 197, 198, 199], name: "Wings"},
	{range: [150], name: "Strange Ears"},
	{range: [200], name: "Wrinkled Skin"}
];

var bodyFunctions = [
	{range: [201, 202], name: "Adhesive Touch"},
	{range: [219], name: "Cocoon"},
	{range: [203, 204], name: "Allergies"},
	{range: [220, 221], name: "Cold Blooded"},
	{range: [205, 206], name: "Ambidextrous"},
	{range: [222, 223], name: "Colour Blind"},
	{range: [207], name: "Anaerobic"},
	{range: [224], name: "Cracking Joints"},
	{range: [208], name: "Aquatic Adaptation"},
	{range: [225], name: "Deaf"},
	{range: [209], name: "Bad Breath"},
	{range: [226, 227], name: "Decreased Metabolism"},
	{range: [210, 211, 212], name: "Bioluminescent"},
	{range: [228, 229, 230, 231, 232], name: "Decreased Physical Capability"},
	{range: [213], name: "Blind"},
	{range: [233], name: "Defensive Barbs"},
	{range: [214], name: "Blood Substitution"},
	{range: [234], name: "Diabetes"},
	{range: [215], name: "Buoyancy"},
	{range: [235], name: "Disease Carrier"},
	{range: [216, 217], name: "Chameleoline Skin"},
	{range: [236, 237], name: "Double Jointed"},
	{range: [218], name: "Chronic Pain"},
	{range: [238, 239], name: "Early Maturation"},
	{range: [240], name: "Efficient Digestion"},
	{range: [295], name: "Ink"},
	{range: [241, 242], name: "Electrical Generation"},
	{range: [296], name: "Kidney Stones"},
	{range: [243, 244], name: "Electromagnetic Disruption"},
	{range: [297], name: "Light Dependency"},
	{range: [245], name: "Enhanced Musculature"},
	{range: [298], name: "Light Generation"},
	{range: [246, 247], name: "Enlarging Mouth"},
	{range: [299], name: "Light Sensitivity"},
	{range: [248], name: "Excretion"},
	{range: [300], name: "Long Life"},
	{range: [249], name: "Explosive Death"},
	{range: [301, 302], name: "Low Pain Threshold"},
	{range: [250], name: "Extensible Limbs"},
	{range: [303], name: "Low Sex Drive"},
	{range: [251], name: "Fast Hair Growth"},
	{range: [304, 305], name: "Malformed Mouth"},
	{range: [252], name: "Fragrant"},
	{range: [306], name: "Malleable Body"},
	{range: [253], name: "Frog Tongue"},
	{range: [307], name: "Malleable Features"},
	{range: [254], name: "Fruit"},
	{range: [308], name: "Microscopic Vision"},
	{range: [255], name: "G-Tolerance"},
	{range: [309], name: "Mute"},
	{range: [256], name: "Gas Bag"},
	{range: [310], name: "Myopia"},
	{range: [257], name: "Gas Emission"},
	{range: [311], name: "Nerve Cut, Off"},
	{range: [258, 259], name: "Gills and Lungs"},
	{range: [312], name: "No Pain Receptors"},
	{range: [260], name: "Hangover Resistance"},
	{range: [313], name: "No Sense of Smell or Taste"},
	{range: [261, 262], name: "Heightened Hearing"},
	{range: [314], name: "No Sense of Touch"},
	{range: [263, 264], name: "Heightened Sense of Smell and Taste"},
	{range: [315], name: "Oversexed"},
	{range: [265, 266], name: "Heightened Sense of Touch"},
	{range: [316], name: "Paraplegic"},
	{range: [267, 268], name: "Hemophilia"},
	{range: [317, 318], name: "Parasite Infestation"},
	{range: [269], name: "Hermaphrodite"},
	{range: [319], name: "Parthenogenesis"},
	{range: [270], name: "Hermaphromorph"},
	{range: [320], name: "Performance Enhancement"},
	{range: [271], name: "High Body Temperature"},
	{range: [321], name: "Permeable Skin"},
	{range: [272, 273], name: "High Pain Threshold"},
	{range: [322, 323, 324], name: "Pheromones"},
	{range: [274], name: "Hollow Bones"},
	{range: [325], name: "Photosynthetic"},
	{range: [275], name: "Horrible Stench"},
	{range: [326], name: "Poison Glands"},
	{range: [276], name: "Hyperadrenal Gland"},
	{range: [327], name: "Poison Susceptibility"},
	{range: [277], name: "Hyperopia"},
	{range: [328, 329], name: "Poor Respiration"},
	{range: [278], name: "Immune to Disease"},
	{range: [330], name: "Pouched Cheeks"},
	{range: [279], name: "Immune to Poison"},
	{range: [331], name: "Powerful Jaws"},
	{range: [280], name: "Increased Appendix Size"},
	{range: [332], name: "Powerful Legs"},
	{range: [281], name: "Increased Heart and Lung Size"},
	{range: [333, 334], name: "Prehensile Feet"},
	{range: [282, 283], name: "Increased Metabolism"},
	{range: [335], name: "Prehensile Hair"},
	{range: [284, 285, 286, 287, 288], name: "Increased Physical Capability"},
	{range: [336, 337], name: "Premature Aging"},
	{range: [289], name: "Increased Susceptibility to Illness"},
	{range: [338], name: "Prey Scent"},
	{range: [290], name: "Independently Focusable Eyes"},
	{range: [339], name: "Protected Senses"},
	{range: [291], name: "Infected"},
	{range: [340], name: "Pseudopods"},
	{range: [292], name: "Infertile"},
	{range: [341], name: "Quadriplegic"},
	{range: [293], name: "Inflation"},
	{range: [342], name: "Radar"},
	{range: [294], name: "Infravision"},
	{range: [343], name: "Reflective Skin"},
	{range: [344, 345, 346], name: "Regeneration"},
	{range: [373], name: "Structural Weakness"},
	{range: [347], name: "Respiratory Filters"},
	{range: [374], name: "Suckers"},
	{range: [348], name: "Roots and Vines"},
	{range: [375, 376], name: "Telescopic Vision"},
	{range: [349], name: "Rotating Body Part"},
	{range: [377, 378], name: "Temperature Resistance"},
	{range: [350], name: "Rotting Flesh"},
	{range: [379, 380], name: "Temperature Sensitivity"},
	{range: [351], name: "Rubber Bones"},
	{range: [381], name: "Thin Skin"},
	{range: [352], name: "Rubbery Skin"},
	{range: [382], name: "Total Healing"},
	{range: [353], name: "Saliva Substitution"},
	{range: [383], name: "Toxic"},
	{range: [354], name: "Salt Drinker"},
	{range: [384], name: "Toxin Resistance"},
	{range: [355], name: "Sanitized Metabolism"},
	{range: [385], name: "Trail of Slime"},
	{range: [356], name: "Shapechanger"},
	{range: [386], name: "Tremor Sense"},
	{range: [357], name: "Shedding"},
	{range: [387], name: "Tunnel Vision"},
	{range: [358], name: "Short Life"},
	{range: [388], name: "Ultravision"},
	{range: [359, 360], name: "Silent Movement"},
	{range: [389], name: "Uncontrollable Flatulence"},
	{range: [361], name: "Silk Production"},
	{range: [390, 391], name: "Venomous Bite"},
	{range: [362, 363], name: "Slow Healer"},
	{range: [392], name: "Ventriloquist"},
	{range: [364, 365], name: "Sonar"},
	{range: [393], name: "Vents"},
	{range: [366], name: "Sonic Blast"},
	{range: [394], name: "Voluminous Lungs"},
	{range: [367], name: "Sound Mimicry"},
	{range: [395], name: "Vomits at Will"},
	{range: [368], name: "Spinning"},
	{range: [396], name: "Water Dependency"},
	{range: [369], name: "Spore Cloud"},
	{range: [397], name: "Water, Soluble Skin"},
	{range: [370], name: "Sprint"},
	{range: [398], name: "Weak Spot"},
	{range: [371], name: "Stiff Joints"},
	{range: [399], name: "Wet Skin"},
	{range: [372], name: "Strong Skeleton"},
	{range: [400], name: "Wounding Genitals"}
];

var mindBehaviours = [
	{range: [401], name: "Addicted"},
	{range: [416], name: "Controlled by Stars"},
	{range: [402, 403], name: "Addictive Personality"},
	{range: [417], name: "Daylight Stasis"},
	{range: [404], name: "Always Afraid"},
	{range: [418], name: "Deep Sleeper"},
	{range: [405], name: "Anxious"},
	{range: [419], name: "Degenerate Gambler"},
	{range: [406], name: "Berserker"},
	{range: [420], name: "Dependency"},
	{range: [407], name: "Blood Rage"},
	{range: [421, 422], name: "Depression"},
	{range: [408], name: "Breakdowns"},
	{range: [423], name: "Drone"},
	{range: [409], name: "Burrower"},
	{range: [424], name: "Drone Producer"},
	{range: [410, 411], name: "Carnivore"},
	{range: [425, 426], name: "Eating Disorder"},
	{range: [412], name: "Code of Honour"},
	{range: [427], name: "Egg Layer"},
	{range: [413], name: "Compulsive Behaviour"},
	{range: [428], name: "Excessive Sleeper"},
	{range: [414], name: "Compulsive Liar"},
	{range: [429], name: "External Digestion"},
	{range: [415], name: "Contrarian"},
	{range: [430], name: "Faith"},
	{range: [431], name: "Fear of Sacred Objects"},
	{range: [466, 467], name: "Omnivore"},
	{range: [432], name: "Fits and Seizures"},
	{range: [468], name: "Outbursts"},
	{range: [433], name: "Glossolalia"},
	{range: [469], name: "Pacifist"},
	{range: [434], name: "Hallucinations"},
	{range: [470], name: "Paranoia"},
	{range: [435, 436], name: "Headaches"},
	{range: [471], name: "Periodic Amnesia"},
	{range: [437, 438], name: "Herbivore"},
	{range: [472, 473, 474], name: "Phobia"},
	{range: [439], name: "Hibernating"},
	{range: [475], name: "Physical Coward"},
	{range: [440, 441], name: "Highly Social"},
	{range: [476], name: "Pyromania"},
	{range: [442], name: "Hoarder"},
	{range: [477, 478], name: "Restricted Diet"},
	{range: [443], name: "Honest"},
	{range: [479], name: "Sadism"},
	{range: [444, 445], name: "Hunting Instinct"},
	{range: [480], name: "Schizophrenia"},
	{range: [446], name: "Hypochondria"},
	{range: [481], name: "Sexual Fetish"},
	{range: [447], name: "Hysterical Injury"},
	{range: [482], name: "Sexual Neurosis"},
	{range: [448], name: "Irrational Hatred"},
	{range: [483], name: "Sexual Prowess"},
	{range: [449], name: "Kleptomania"},
	{range: [484], name: "Short Fuse"},
	{range: [450], name: "Largesse"},
	{range: [485], name: "Shuddering"},
	{range: [451, 452], name: "Manic"},
	{range: [486], name: "Shy"},
	{range: [453, 454], name: "Manic Depressive"},
	{range: [487], name: "Silly Voice"},
	{range: [455], name: "Masochism"},
	{range: [488], name: "Silly Walk"},
	{range: [456], name: "Mental Block"},
	{range: [489], name: "Sleepwalking"},
	{range: [457], name: "Migratory"},
	{range: [490, 491], name: "Slovenly"},
	{range: [458], name: "Motherliness"},
	{range: [492], name: "Sociopathic"},
	{range: [459], name: "Multi, Stage Lifespan"},
	{range: [493], name: "Strange Sound"},
	{range: [460], name: "Multiple Personalities"},
	{range: [494], name: "Stuttering"},
	{range: [461], name: "Narcolepsy"},
	{range: [495, 496], name: "Territorial"},
	{range: [462], name: "Nightmares"},
	{range: [497, 498], name: "Tidy"},
	{range: [463, 464], name: "Nocturnal"},
	{range: [499], name: "Transgendered"},
	{range: [465], name: "Obsessive"},
	{range: [500], name: "Vengeful"}
];

var mindCognition = [
	{range: [501, 502], name: "Animal Friendship"},
	{range: [526], name: "Dual Attention"},
	{range: [503], name: "Anticipation"},
	{range: [527, 528], name: "Dual Brain"},
	{range: [504, 505, 506, 507, 508], name: "Attention Deficit Disorder"},
	{range: [529, 530, 531, 532, 533], name: "Dyslexia"},
	{range: [509], name: "Autobiographical Memory"},
	{range: [534, 535], name: "Earthquake Prediction"},
	{range: [510, 511, 512], name: "Body Sense"},
	{range: [536], name: "Editorial Evaluation"},
	{range: [513], name: "Computer Brain"},
	{range: [537], name: "Eidetic Memory"},
	{range: [514, 515], name: "Cultural Flexibility"},
	{range: [538, 539, 540], name: "Emotionless"},
	{range: [516, 517, 518, 519, 520], name: "Decreased Mental Capability"},
	{range: [541], name: "Enhance Mutations"},
	{range: [521, 522, 523, 524], name: "Directional Sense"},
	{range: [542, 543], name: "Enhanced Nervous System"},
	{range: [525], name: "Dreamless"},
	{range: [544, 545, 546, 547, 548], name: "Enhanced Senses"},
	{range: [549], name: "Genetic Memory"},
	{range: [577], name: "No Visual Memory"},
	{range: [550, 551], name: "Heightened Olfactory Memory"},
	{range: [578, 579, 580], name: "Quick Learner"},
	{range: [552], name: "Hive Mind"},
	{range: [581, 582], name: "Radio Communication"},
	{range: [553, 554, 555], name: "Increased Brain Size"},
	{range: [583], name: "Romantic Rapport"},
	{range: [556, 557, 558, 559, 560], name: "Increased Mental Capability"},
	{range: [584, 585], name: "Sense Interference"},
	{range: [561, 562, 563, 564], name: "Insomnia"},
	{range: [586, 587], name: "Social Perception"},
	{range: [565], name: "Intuition"},
	{range: [588], name: "Socially Inept"},
	{range: [566, 567, 568], name: "Linguistic Aptitude"},
	{range: [589, 590, 591], name: "Spatial Perception"},
	{range: [569, 570], name: "Linguistic Mimic"},
	{range: [592, 593], name: "Speed Reader"},
	{range: [571], name: "Lucid Dreaming"},
	{range: [594, 595], name: "Time Sense"},
	{range: [572, 573], name: "Mechanical Intuition"},
	{range: [596], name: "Transfer Memories"},
	{range: [574], name: "Mindless"},
	{range: [575, 576], name: "Natural Leader"},
	{range: [597, 598, 599, 600], name: "Weather Sense"}
];

var psychicPowers = [
	{range: [601], name: "Animal Control"},
	{range: [638, 639], name: "Healing"},
	{range: [602], name: "Anti, Charisma"},
	{range: [640], name: "Heat Drain"},
	{range: [603], name: "Attack Reversal"},
	{range: [641], name: "Hostility Field"},
	{range: [604, 605], name: "Aura Reading"},
	{range: [642, 643, 644], name: "Hypnotic"},
	{range: [606], name: "Block Senses"},
	{range: [645], name: "Illusionist"},
	{range: [607, 608], name: "Cause Fear"},
	{range: [646], name: "Illusory Surroundings"},
	{range: [609], name: "Cause Insanity"},
	{range: [647], name: "Implant Memories"},
	{range: [610, 611], name: "Cause Pain"},
	{range: [648], name: "Inhibiting Field"},
	{range: [612, 613], name: "Charm"},
	{range: [649, 650], name: "Levitation"},
	{range: [614, 615], name: "Clairaudience"},
	{range: [651], name: "Life Leech"},
	{range: [616, 617, 618], name: "Clairvoyance"},
	{range: [652], name: "Light Manipulation"},
	{range: [619], name: "Commanding Voice"},
	{range: [653], name: "Magnetic Control"},
	{range: [620, 621], name: "Confuse"},
	{range: [654, 655], name: "Mass Mind"},
	{range: [622], name: "Create Emotions"},
	{range: [656, 657], name: "Mental Blast"},
	{range: [623], name: "Cryokinesis"},
	{range: [658, 659], name: "Mental Suggestion"},
	{range: [624], name: "Death Field Generation"},
	{range: [660], name: "Mind Attack"},
	{range: [625], name: "Ectoplasmic Hands"},
	{range: [661, 662, 663], name: "Pain Broadcast"},
	{range: [626, 627, 628], name: "Emotional Projection"},
	{range: [664], name: "Precognition"},
	{range: [629], name: "Enter Mind"},
	{range: [665, 666], name: "Psychic Broadcast"},
	{range: [630], name: "Erase Memories"},
	{range: [667, 668], name: "Psychic Cultural Adaptation"},
	{range: [631], name: "Familiarity"},
	{range: [669, 670, 671], name: "Psychic Detection"},
	{range: [632], name: "Fire in the Head"},
	{range: [672, 673, 674], name: "Psychic Empathy"},
	{range: [633, 634, 635], name: "Firewalker"},
	{range: [675], name: "Psychic Invisibility"},
	{range: [636, 637], name: "Heal Brain"},
	{range: [676], name: "Psychic Mirror"},
	{range: [677, 678, 679], name: "Psychic Vampire"},
	{range: [688], name: "Symbiotic Control"},
	{range: [680, 681], name: "Psychoanalyze"},
	{range: [689, 690, 691], name: "Telekinesis"},
	{range: [682], name: "Psychometry"},
	{range: [692], name: "Telekinetic Flight"},
	{range: [683], name: "Send Dreams"},
	{range: [693, 694, 695, 696], name: "Telepathy"},
	{range: [684, 685], name: "Sixth Sense"},
	{range: [697], name: "Teleport"},
	{range: [686], name: "Stunning Blast"},
	{range: [698], name: "Teleport Object"},
	{range: [687], name: "Summon"},
	{range: [699, 700], name: "Time Distortion"}
];

var supernaturalAttributes = [
	{range: [701], name: "Ability Transfer"},
	{range: [745], name: "Charred Body"},
	{range: [702, 703], name: "Absorb Inanimate Properties"},
	{range: [746], name: "Compulsive Counting"},
	{range: [704, 705], name: "Absorb Mental Properties"},
	{range: [747], name: "Computer Link"},
	{range: [706], name: "Addictive Smoke"},
	{range: [748, 749], name: "Conjuration"},
	{range: [707], name: "Air Swimmer"},
	{range: [750], name: "Control Clocks"},
	{range: [708], name: "Alteration Ray"},
	{range: [751], name: "Control Crowds"},
	{range: [709, 710], name: "Alternate Inorganic Form"},
	{range: [752, 753, 754], name: "Control Earth"},
	{range: [711, 712, 713], name: "Animal Shapechange"},
	{range: [755, 756, 757], name: "Control Light"},
	{range: [714, 715], name: "Animate Objects"},
	{range: [758, 759, 760], name: "Control Liquid"},
	{range: [716], name: "Animated Skin"},
	{range: [761, 762], name: "Control Machines"},
	{range: [717, 718], name: "Animated Tattoos"},
	{range: [763, 764, 765], name: "Control Plants"},
	{range: [719], name: "Arcane Knowledge"},
	{range: [766], name: "Control Reputation"},
	{range: [720], name: "Arcane Tracking"},
	{range: [767], name: "Corpse Psychometry"},
	{range: [721, 722], name: "Armoured Skin"},
	{range: [768], name: "Cosmic Awareness"},
	{range: [723], name: "Astral Projection"},
	{range: [769], name: "Create Darkness"},
	{range: [724], name: "Aura of Disgust"},
	{range: [770, 771], name: "Create Gas"},
	{range: [725, 726], name: "Aura of Fear"},
	{range: [772, 773, 774, 775], name: "Crossbreed"},
	{range: [727, 728], name: "Aura of Light"},
	{range: [775], name: "Crystalline Body"},
	{range: [729], name: "Become Two, Dimensional"},
	{range: [776], name: "Danger Teleport"},
	{range: [730, 731, 732], name: "Bend Light"},
	{range: [777], name: "Darksight"},
	{range: [733], name: "Bio, Tech Assimilation"},
	{range: [778], name: "Demonic Appearance"},
	{range: [734], name: "Blurry"},
	{range: [779, 780, 781], name: "Demonic Phenomena"},
	{range: [735], name: "Book"},
	{range: [782], name: "Demonologist"},
	{range: [736], name: "Book, Viewing"},
	{range: [783], name: "Density Control"},
	{range: [737], name: "Brain Washer"},
	{range: [784], name: "Devolver"},
	{range: [738, 739, 740], name: "Breath Weapon"},
	{range: [785], name: "Dimensional/Temporal Instability"},
	{range: [741], name: "Burning Body"},
	{range: [786, 787], name: "Dissent Parasite"},
	{range: [742], name: "Burning Inside"},
	{range: [788], name: "Divine Avatar"},
	{range: [743], name: "Cannot Cross Running Water"},
	{range: [789], name: "Divisional Body Segments"},
	{range: [744], name: "Cause Sleep"},
	{range: [790], name: "Duplication"},
	{range: [791, 792], name: "Eat Anything"},
	{range: [847], name: "Infinite Endurance"},
	{range: [793], name: "Elasticity"},
	{range: [848, 849], name: "Inspiring Aura"},
	{range: [794], name: "Electrical Travel"},
	{range: [850, 851], name: "Intangibility"},
	{range: [795], name: "Elemental Body"},
	{range: [852], name: "Invincible Buddha"},
	{range: [796], name: "Energy Absorption"},
	{range: [853, 854, 855], name: "Invisibility"},
	{range: [797, 798, 799], name: "Energy Blast"},
	{range: [856], name: "Invulnerable"},
	{range: [800, 801], name: "Energy Negation Field"},
	{range: [857, 858], name: "Invulnerable to Weapons"},
	{range: [802], name: "Energy Redirection"},
	{range: [859], name: "Iron Teeth and Nails"},
	{range: [803], name: "Energy Sensitivity"},
	{range: [860], name: "Kinetic Absorption"},
	{range: [804], name: "Entropic Precision"},
	{range: [861, 862], name: "Liquid Form"},
	{range: [805, 806, 807], name: "Ethereal Projection"},
	{range: [863, 864], name: "Magic Resistance"},
	{range: [808], name: "Evil Eye"},
	{range: [865], name: "Magical Affinity"},
	{range: [809], name: "Exorcist"},
	{range: [866], name: "Magnetic"},
	{range: [810], name: "Explode Objects"},
	{range: [867], name: "Manikin"},
	{range: [811], name: "Eye Scrying"},
	{range: [868], name: "Manipulate Gravity"},
	{range: [812], name: "Face of a Demon"},
	{range: [869], name: "Material Transparency"},
	{range: [813], name: "Face of a Demon, God"},
	{range: [870, 871], name: "Mechanoid"},
	{range: [814], name: "False Body"},
	{range: [872], name: "Mercreatures"},
	{range: [815], name: "Featureless Face"},
	{range: [873], name: "Metal Skin"},
	{range: [816], name: "Flaming Skull Face"},
	{range: [874], name: "Mind Cannibal"},
	{range: [817], name: "Flammable Skin"},
	{range: [875], name: "Molecular Disruption"},
	{range: [818], name: "Fleshcrafter"},
	{range: [876], name: "Molecular Sense"},
	{range: [819, 820, 821], name: "Force Field"},
	{range: [877], name: "Multiplication"},
	{range: [822], name: "Fortune Teller"},
	{range: [878, 879], name: "Mutant Detection"},
	{range: [823], name: "Freezing Body"},
	{range: [880, 881], name: "Mystical Third Eye"},
	{range: [824], name: "Gaseous Form"},
	{range: [882], name: "Nightmare Portal"},
	{range: [825], name: "Ghost Talker"},
	{range: [883, 884], name: "No Reflection"},
	{range: [826], name: "Glittering"},
	{range: [885, 886], name: "No Shadow"},
	{range: [827], name: "Glow"},
	{range: [887], name: "Object Bound"},
	{range: [828], name: "Halo"},
	{range: [888], name: "Object Mimic"},
	{range: [829, 830], name: "Heal Others"},
	{range: [889, 890], name: "Patronage"},
	{range: [831], name: "Historical Viewing"},
	{range: [891], name: "Perfect Regeneration"},
	{range: [832], name: "Homunculus"},
	{range: [892, 893], name: "Petrifying Gaze"},
	{range: [833, 834], name: "Illusion Generation"},
	{range: [894], name: "Physical Mimic"},
	{range: [835], name: "Illusory Features"},
	{range: [895], name: "Planar Travel"},
	{range: [836, 837], name: "Immortal"},
	{range: [896], name: "Possession"},
	{range: [838, 839], name: "Immune to Cold"},
	{range: [897], name: "Power Duplication"},
	{range: [840, 841], name: "Immune to Energy"},
	{range: [898, 899], name: "Power Source"},
	{range: [842, 843], name: "Immune to Heat"},
	{range: [900], name: "Power Theft"},
	{range: [844, 845], name: "Immune to Illusions"},
	{range: [901, 902, 903], name: "Pyrokinesis"},
	{range: [846], name: "Incorporated Objects"},
	{range: [904, 905], name: "Radioactive"},
	{range: [906], name: "Removable Eyes"},
	{range: [957], name: "Susceptible to Possession"},
	{range: [907, 908], name: "Repulsed by Food"},
	{range: [958], name: "Symbol Bondage"},
	{range: [909], name: "Sacred Aura"},
	{range: [959, 960], name: "Taboo"},
	{range: [910, 911], name: "Saturated with Magical Energy"},
	{range: [961, 962], name: "Telepathic Communication"},
	{range: [912], name: "Secret Communication"},
	{range: [963, 964], name: "Telltale"},
	{range: [913], name: "Seep"},
	{range: [965], name: "Tomb Bondage"},
	{range: [914, 915], name: "Sense Evil"},
	{range: [966], name: "Total Chameleon"},
	{range: [916, 917, 918], name: "Sense Fear"},
	{range: [967, 968], name: "Totem Animal"},
	{range: [919, 920], name: "Sense Good"},
	{range: [969], name: "Trackless"},
	{range: [921, 922, 923], name: "Sense Lies"},
	{range: [970], name: "Transform Material"},
	{range: [924, 925], name: "Sensitive to Metal"},
	{range: [971, 972], name: "Transformation"},
	{range: [926, 927], name: "Sensitive to Sunlight"},
	{range: [973], name: "Translucent"},
	{range: [928], name: "Shadow Walk"},
	{range: [974], name: "Transmute Matter"},
	{range: [929], name: "Skinwalker"},
	{range: [975], name: "Transparent Flesh"},
	{range: [930], name: "Speak with Animals"},
	{range: [976], name: "Tunnelling"},
	{range: [931], name: "Spell Ability"},
	{range: [977], name: "Unbound"},
	{range: [932], name: "Spirit Enmity"},
	{range: [978, 979], name: "Undead"},
	{range: [933, 934], name: "Spirit Medium"},
	{range: [980], name: "Unwilling Medium"},
	{range: [935, 936], name: "Stable Balance"},
	{range: [981, 982, 983], name: "Vampiric"},
	{range: [937], name: "Stigmata"},
	{range: [984, 985], name: "Walk on Water"},
	{range: [938, 939, 940], name: "Superhuman Charisma"},
	{range: [986], name: "War Sense"},
	{range: [941, 942, 943], name: "Superhuman Intellect"},
	{range: [987, 988, 989, 990, 991], name: "Weakness"},
	{range: [944], name: "Superhuman Perception"},
	{range: [992, 993], name: "Weather Manipulation"},
	{range: [945, 946, 947], name: "Superhuman Reflexes"},
	{range: [994, 995, 996, 997], name: "Werecreatures"},
	{range: [948, 949, 950], name: "Superhuman Speed"},
	{range: [998], name: "X-Ray Vision"},
	{range: [951, 952, 953], name: "Superhuman Strength"},
	{range: [999], name: "Zombie Master"},
	{range: [954, 955, 956], name: "Superhuman Toughness"},
	{range: [1000], name: "Zone of Silence"}
];

var alternateLocomotion = [
	{range: [1, 2, 3], name: pick(creatures) + " legs"},
	{range: [13, 14, 15], name: pick(creatures) + " body "},
	{range: [4, 5, 6, 7], name: "Quadruped"},
	{range: [16], name: "Bouncing"},
	{range: [8, 9, 10], name: "Slithering"},
	{range: [17], name: "Fronds"},
	{range: [11], name: "Mass of tendrils or tentacles"},
	{range: [18, 19], name: "Hovering"},
	{range: [12], name: "Pseudopods"},
	{range: [20], name: "Teleporting"}
];

var animalFeet = [
	{range: [1], name: "Bird feet."},
	{range: [2], name: "Hooves."},
	{range: [3], name: "Mammalian paws."},
	{range: [4], name: "Reptilian claws."},
	{range: [5], name: "Stumps."},
	{range: [6], name: "Tentacles."}
];

var handFeet = [
	{range: [1], name: "Clumsy hands. "},
	{range: [3], name: "Human hands."},
	{range: [2], name: "Dextrous creatures hands. "},
	{range: [4], name: "Same as creatures."},
	{range: [5, 6], name: "Fully bipedal. "},
	{range: [7], name: "Stooped bipedal."},
	{range: [8, 9], name: "Half creatures, half human. "},
	{range: [10], name: "Same as creatures."}
];

var anthropomorphicAppearance = [
	{range: [1, 2, 3], name: "Body is half-human, facial features are all creatures."},
	{range: [4], name: "Human that resembles the creatures."},
	{range: [5, 6], name: "Half creatures, half human."},
	{range: [7, 8], name: pick(handFeet)},
];

var armour = [
	{range: [1], name: "Blubber"},
	{range: [4], name: "Hard shell"},
	{range: [2], name: "Bone plate"},
	{range: [5], name: "Scale"},
	{range: [3], name: "Carapace"},
	{range: [6], name: "Thick skin"}
];

var bodyParts = [
	{range: [1, 2, 3], name: "Abdomen"},
	{range: [39], name: "Left foot"},
	{range: [76, 77, 78], name: "Right arm"},
	{range: [4, 5, 6, 7, 8], name: "Abdomen and legs"},
	{range: [40], name: "Left hand"},
	{range: [79], name: "Right ear"},
	{range: [9, 10, 11, 12], name: "Back/spine"},
	{range: [41, 42, 43], name: "Left leg"},
	{range: [80, 81, 82], name: "Right eye"},
	{range: [13, 14], name: "Buttocks"},
	{range: [44, 45, 46, 47], name: "Mouth"},
	{range: [83], name: "Right foot"},
	{range: [15, 16, 17, 18, 19], name: "Chest"},
	{range: [48, 49, 50], name: "Nose or snout"},
	{range: [84], name: "Right hand"},
	{range: [20, 21, 22, 23], name: "Face"},
	{range: [51, 52, 53, 54, 55, 56], name: "Pair of arms"},
	{range: [85, 86, 87], name: "Right leg"},
	{range: [24, 25, 26], name: "Genitals"},
	{range: [57, 59, 59], name: "Pair of ears"},
	{range: [88, 89], name: "Shoulders"},
	{range: [27, 28, 29, 30, 31], name: "Head"},
	{range: [60, 61, 62, 63], name: "Pair of eyes"},
	{range: [90, 91, 92], name: "Tail"},
	{range: [32, 33, 34], name: "Left arm"},
	{range: [64, 65, 66], name: "Pair of feet"},
	{range: [93, 94, 95], name: "Torso and arms"},
	{range: [35], name: "Left ear"},
	{range: [67, 68, 69], name: "Pair of hands"},
	{range: [96, 97, 98], name: "Torso and head"},
	{range: [36, 37, 38], name: "Left eye"},
	{range: [70, 71, 72, 73, 74, 75], name: "Pair of legs"},
	{range: [99, 100], name: "Torso, head, and both/all arms"}
];

var colours = [
	{range: [1], name: "Amber"},
	{range: [35], name: "Gold"},
	{range: [68], name: "Pumpkin"},
	{range: [2], name: "Apricot"},
	{range: [36], name: "Green"},
	{range: [69], name: "Purple"},
	{range: [3], name: "Aqua"},
	{range: [37], name: "Green-yellow"},
	{range: [70], name: "Red"},
	{range: [4], name: "Aquamarine"},
	{range: [38], name: "Grey"},
	{range: [71], name: "Red-brown"},
	{range: [5], name: "Auburn"},
	{range: [39], name: "Indigo"},
	{range: [72], name: "Red-violet"},
	{range: [6], name: "Azure"},
	{range: [40], name: "Iridescent colour"},
	{range: [73], name: "Rose"},
	{range: [7], name: "Beige"},
	{range: [41], name: "Ivory"},
	{range: [74], name: "Ruddy"},
	{range: [8], name: "Black"},
	{range: [42], name: "Jade"},
	{range: [75], name: "Russet"},
	{range: [9], name: "Blue"},
	{range: [43], name: "Jale"},
	{range: [76], name: "Rust"},
	{range: [10], name: "Blue-green"},
	{range: [44], name: "Jet"},
	{range: [77], name: "Salmon"},
	{range: [11], name: "Blue-grey"},
	{range: [45], name: "Khaki"},
	{range: [78], name: "Scarlet"},
	{range: [12], name: "Blue-violet"},
	{range: [46], name: "Lavender"},
	{range: [79], name: "Sea green"},
	{range: [13], name: "Brass"},
	{range: [47], name: "Lilac"},
	{range: [80], name: "Sepia"},
	{range: [14], name: "Bronze"},
	{range: [48], name: "Lime"},
	{range: [81], name: "Silver"},
	{range: [15], name: "Brown"},
	{range: [49], name: "Magenta"},
	{range: [82], name: "Sky blue"},
	{range: [16], name: "Bright green"},
	{range: [50], name: "Mahogany"},
	{range: [83], name: "Sparkly colour"},
	{range: [17], name: "Buff"},
	{range: [51], name: "Maroon"},
	{range: [84], name: "Tan"},
	{range: [18], name: "Burgundy"},
	{range: [52], name: "Matte colour"},
	{range: [85], name: "Tangerine"},
	{range: [19], name: "Cerulean"},
	{range: [53], name: "Mauve"},
	{range: [86], name: "Taupe"},
	{range: [20], name: "Charcoal"},
	{range: [54], name: "Metallic colour"},
	{range: [87], name: "Teal"},
	{range: [21], name: "Chartreuse"},
	{range: [55], name: "Mustard yellow"},
	{range: [88], name: "Terra cotta"},
	{range: [22], name: "Copper"},
	{range: [56], name: "Ochre"},
	{range: [89], name: "Turquoise"},
	{range: [23], name: "Cream"},
	{range: [57], name: "Octarine"},
	{range: [90], name: "Two colours shifting"},
	{range: [24], name: "Crimson"},
	{range: [58], name: "Off-white"},
	{range: [91], name: "Ulfire"},
	{range: [25], name: "Cyan"},
	{range: [59], name: "Olive"},
	{range: [92], name: "Ultramarine"},
	{range: [26], name: "Dolm"},
	{range: [60], name: "Orange"},
	{range: [93], name: "Umber"},
	{range: [27], name: "Drab"},
	{range: [61], name: "Orange-red"},
	{range: [94], name: "Verdigris"},
	{range: [28], name: "Emerald"},
	{range: [62], name: "Peach"},
	{range: [95], name: "Vermillion"},
	{range: [29], name: "Forest green"},
	{range: [63], name: "Periwinkle"},
	{range: [96], name: "Violet"},
	{range: [30], name: "Fuchsia"},
	{range: [64], name: "Pink"},
	{range: [97], name: "White"},
	{range: [31], name: "Garrow"},
	{range: [65], name: "Pink-orange"},
	{range: [98], name: "Wisteria"},
	{range: [32], name: "Ginger"},
	{range: [66], name: "Plum"},
	{range: [99], name: "Yellow"},
	{range: [33], name: "Glossy colour"},
	{range: [67], name: "Puce"},
	{range: [34], name: "Glowing colour "},
	{range: [100], name: "Yellow-green"}
];

var ciliaCoverage = [
	{range: [1], name: "Back"},
	{range: [2], name: "Front"},
	{range: [3, 4], name: "Full body"},
	{range: [5, 6], name: "Full body", subtable: bodyParts}
];

var claws = [
	{range: [1], name: "Crab-like claws for hands"},
	{range: [3], name: "Sharp, iron, hard nails"},
	{range: [2], name: "Retractable claws"},
	{range: [4], name: "Talons"}
];

var orifices = [
	{range: [1], name: "Anuses"},
	{range: [5, 6], name: "Eyes"},
	{range: [10], name: "Nostrils"},
	{range: [2, 3], name: "Cloacas/Urethras"},
	{range: [7], name: "Large pores"},
	{range: [11], name: "Siphons or valves"},
	{range: [4], name: "Ears"},
	{range: [8, 9], name: "Mouths"},
	{range: [12], name: "Vaginas"}
];

var resemblance = [
	{range: [1], name: "Bone or cartilage"},
	{range: [4], name: "Erectile tissue"},
	{range: [7], name: "Noses"},
	{range: [2], name: "Coral"},
	{range: [5], name: "Eyestalks"},
	{range: [8, 9], name: "Thumbs"},
	{range: [3], name: "Ears"},
	{range: [6], name: "Fingers or toes."},
	{range: [10], name: "Tongues"}
];

var organs = [
	{range: [1], name: "Bladder and kidneys"},
	{range: [5], name: "Liver and pancreas"},
	{range: [2], name: "Brains"},
	{range: [6], name: "Lungs and respiratory system"},
	{range: [3], name: "Heart and blood circulation"},
	{range: [7], name: "Sense organs"},
	{range: [4], name: "Intestines and stomach"},
	{range: [8], name: "Sets of organs"}
];

var fangs = [
	{range: [1], name: "All teeth sharpened"},
	{range: [4], name: "Rat-like incisors"},
	{range: [2], name: "Long canines"},
	{range: [5], name: "Retractable canines"},
	{range: [3], name: "Needle-like teeth"},
	{range: [6], name: "Tusks"}
];

var fur = [
	{range: [1], name: "Long fur"},
	{range: [3], name: "Short, soft fur"},
	{range: [2], name: "Short, bristly fur"},
	{range: [4], name: "Thick, curly hair"}
];

var horns = [
	{range: [1, 2], name: "One large horn"},
	{range: [9, 10], name: "Three or more large horns"},
	{range: [3, 4], name: "One small horn"},
	{range: [11], name: "Three or more small horns"},
	{range: [5], name: "A rack of dull antlers"},
	{range: [12, 13, 14], name: "Two large, curved horns"},
	{range: [6, 7], name: "A rack of sharp antlers"},
	{range: [15, 16], name: "Two large, straight horns"},
	{range: [8], name: "A rack of velvet, covered antlers"},
	{range: [17, 18, 19, 20], name: "Two small horns"}
];

var weapon = [
	{range: [1], name: "Club (blunt, jagged, or spiked)"},
	{range: [4], name: "Spear or piercing weapon."},
	{range: [2], name: "Flail, lash, or whip"},
	{range: [5], name: "Explosive weapon"},
	{range: [3], name: "Knife or sword, like blades"},
	{range: [6], name: "Ranged weapon"}
];

var leaves = [
	{range: [1], name: "Barbed leaves"},
	{range: [7, 8], name: "Grass"},
	{range: [2, 3], name: "Coniferous needles"},
	{range: [9, 10], name: "Perpetually green leaves"},
	{range: [4, 5], name: "Deciduous leaves"},
	{range: [11], name: "Razor, edged leaves"},
	{range: [6], name: "Fronds"},
	{range: [12], name: "Saw, edged leaves"}
];

var limbs = [
	{range: [1], name: "Arm"},
	{range: [3], name: "Hand"},
	{range: [5], name: "Tail or other"},
	{range: [2], name: "Foot"},
	{range: [4], name: "Leg"},
	{range: [6], name: "Wings or other"}
];

var bodyLocation = [
	{range: [1, 2], name: "Back"},
	{range: [5], name: "Foot"},
	{range: [8], name: "Head"},
	{range: [3], name: "Chest"},
	{range: [6], name: "Groin or hip"},
	{range: [9], name: "Knee"},
	{range: [4], name: "Elbow"},
	{range: [7], name: "Hand"},
	{range: [10], name: "Stomach"}
];

var mane = [
	{range: [1], name: "Mane of feathers"},
	{range: [5, 6], name: "Mane of hair like a lion"},
	{range: [2], name: "Mane of fleshy tentacles"},
	{range: [7], name: "Mane of barbs, quills, or spines"},
	{range: [3, 4], name: "Mane of hair like a horse"},
	{range: [8], name: "Membranous mane like a lizard"}
];

var earlessness = [
	{range: [1, 2], name: "No ears except vibration sensors."},
	{range: [3], name: "No ears whatsoever, internal or external."},
	{range: [4, 6], name: "No external ears (just holes in head)."}
];

var tongue = [
	{range: [1], name: "Extremely thick"},
	{range: [5], name: "Hollow"},
	{range: [2], name: "Extremely long"},
	{range: [6], name: "Parasitic organism"},
	{range: [3], name: "Extremely short"},
	{range: [7], name: "Sharp and blade, like"},
	{range: [4], name: "Forked or pincer, shaped"},
	{range: [8], name: "Tentacle"}
];

var pattern = [
	{range: [1, 2], name: "Banded"},
	{range: [12, 13], name: "Small spots"},
	{range: [3], name: "Belted"},
	{range: [14], name: "Patchy"},
	{range: [4, 5], name: "Camouflage pattern"},
	{range: [15, 16], name: "Small spots"},
	{range: [6, 8], name: "Different colour face or head"},
	{range: [17, 19], name: "Striped"},
	{range: [9, 11], name: "Different colour hands and feet"},
	{range: [20], name: "Whorled"}
];

var texture = [
	{range: [1], name: "Bark or plant material"},
	{range: [7], name: "Hard or soft plastic"},
	{range: [2], name: "Brick, dirt, or stone"},
	{range: [8], name: "Metal"},
	{range: [3], name: "Crystal"},
	{range: [9], name: "Rough fabric"},
	{range: [4], name: "Foam"},
	{range: [10], name: "Sand or sandpaper"},
	{range: [5], name: "Geometric patterns"},
	{range: [11], name: "Smooth and slippery"},
	{range: [6], name: "Glass"},
	{range: [12], name: "Soft fabric"}
];

var duration = [
	{range: [1], name: "Several days"},
	{range: [3], name: "Several months"},
	{range: [2], name: "Several hours"},
	{range: [4], name: "Several weeks"}
];

var tail = [
	{range: [1, 2], name: "Long tail"},
	{range: [5], name: "Scorpion tail (with venom)"},
	{range: [3], name: "Mace tail"},
	{range: [6, 7], name: "Short tail"},
	{range: [4], name: "Prehensile or tentacle tail"},
	{range: [8], name: "Reptile tail"}
];

var tentacles = [
	{range: [1], name: "Tentacles instead of arms"},
	{range: [5], name: "Tentacles on back of body"},
	{range: [2], name: "Tentacles instead of hair"},
	{range: [6], name: "Tentacles on front of body"},
	{range: [3], name: "Tentacles instead of legs"},
	{range: [7], name: "Tentacles on head or face"},
	{range: [4], name: "Tentacles on arms and legs"},
	{range: [8], name: "Tentacles on two locations"}
];

var weapons = [
	{range: [1, 2], name: "Blade"},
	{range: [4], name: "Hook"},
	{range: [7], name: "Scissor"},
	{range: [3], name: "Blunt"},
	{range: [5, 6], name: "Pincer"},
	{range: [8], name: "Stinger"}
];

var wings = [
	{range: [1], name: "Alien wings"},
	{range: [5], name: "Glider wings"},
	{range: [2], name: "Avian wings"},
	{range: [6], name: "Gossamer wings"},
	{range: [3], name: "Bat wings"},
	{range: [7], name: "Insect wings"},
	{range: [4], name: "Dragonfly wings"},
	{range: [8], name: "Angel wings"}
];


var mutationTableIndex = [
	{name: 'Body: Form', range: _.range(1, 201), subtable: bodyForm},
	{name: 'Body: Function', range: _.range(201, 401), subtable: bodyFunctions},
	{name: 'Mind: Behaviours', range: _.range(401, 501), subtable: mindBehaviours},
	{name: 'Mind: Cognition', range: _.range(501, 601), subtable: mindCognition},
	{name: 'Psychic Powers', range: _.range(601, 701), subtable: psychicPowers},
	{name: 'Supernatural Attributes', range: _.range(701, 1001), subtable: supernaturalAttributes}	
];

var describe = {
	"Albino": "This mutant has no natural pigment colouration, so its skin and hair are white to pinkish, and its eyes are blue, pink, or red. This makes the mutant acutely vulnerable to sunburn.",
	"Alternate Locomotion": "Instead of walking on two legs (or whatever is normal for its species), this mutant has " + pick(alternateLocomotion) + " locomotion. Its old method of travel is no longer effective.",
	"Amorphous": "This mutant is a blob, probably without distinguishable limbs or extremities.",
	"Animal Feet": "This mutant has " + pick(animalFeet),
	"Antennae": "This mutant has a set of two or more antennae extending from its head, which it can use to feel and possibly smell and taste or otherwise augment its various senses.",
	"Anthropomorphic Animal": "This mutant appears to be an anthropomorphic, talking " + pick(creatures) + ". Appearance: " + pick(anthropomorphicAppearance) + ".",
	"Armour": "This mutant is protected by " + pick(armour) + " armour.",
	"Atrophied or Malformed Part": "This mutant has an atrophied or malformed " + pick(bodyParts),
	"Attractive": "This mutant is considered incredibly attractive, physically perfect, and sexually desirable by other members of its species (barring any other mutations that might spoil such beauty).",
	"Backwards Parts": "This mutant has a " + pick(bodyParts) + " attached backwards.",
	"Beak": "This mutant has a beak instead of the mouth that is normal for its species. If it normally has a beak, now it has two.",
	"Bestial Face": "This mutant has a face that perfectly or superficially resembles that of a " + pick(creatures),
	"Birthmark": "This mutant has a prominent " + pick(bodyParts) + " birthmark resembling a wine stain, or other appropriate discoloration.",
	"Body Barbs": "Bone spurs grow out of this mutant’s " + pick(bodyParts) + ", and can be used as weapons.",
	"Boils and Sores": "This mutant’s body is covered in painful and irritating boils and sores that leak fluids and are prone to infection.",
	"Bristles": "This mutant has coarse bristly hair all over it that offers some small amount of protection.",
	"Bulging Eyes": "This mutant’s eyes are large and bulbous.",
	"Cat's Eyes": "This mutant’s pupils are slit like a cat’s eyes, increasing its night vision.",
	"Changing Colours": "This mutant physically changes colour, based on temperament and temperature, alternating between " + pick(colours) + ", " + pick(colours) + ", " + pick(colours) + ", " + pick(colours) + ", " + pick(colours) + ", and " + pick(colours),
	"Cilia": "This mutant, or part of it, is covered on its " + pick(ciliaCoverage) + " with tiny, movable, hair-like appendages or tentacles that probably keep it free from dirt and constantly move food toward its mouth.",
	"Claws": "This mutant has " + pick(claws) + " that it can use for weapons.",
	"Clothes": "This mutant appears to be wearing clothes, but this is actually just the appearance of its naked skin. It can still wear clothes over top of its garment-resembling skin, of course.",
	"Clubfoot": "One of this mutant’s feet is deformed and gimpy. It is probably shorter than the other, impedes proper movement, and makes shoe purchasing more difficult.",
	"Complex Mouthparts": "This mutant has additional complex parts around its mouth, like an arthropod. This can include external chelicerae, mandibles, maxillae, a proboscis, a radula, or other parts.",
	"Covered in Orifices": "This mutant’s body is covered in " + pick(orifices),
	"Crest": "This mutant has a crest on top of its head, made of rigid flesh, bone, cartilage, feathers, horn, scales, or other material.",
	"Crown": "This mutant has a crown of " + pick(resemblance) + " encircling its head.",
	"Diffused Organs": "The " + pick(organs) + " are diffused, spread out in a larger system within the mutant’s body, instead of concentrated in one space. This makes the organ(s) much more resistant to injury, as it can continue to operate when a part of it is wounded.",
	"Doppelgänger": "This mutant looks exactly like one or more other individuals it may or may not know.",
	"Double Mouth": "This mutant has an interior mouth inside of an exterior mouth. The interior mouth may or may not be extensible. It cannot be seen when the exterior mouth is closed.",
	"Enormously Fat": "This mutant is so corpulent that it can no longer run and likely has trouble walking.",
	"Exotic Genitalia": "This mutant’s sexual organs include unusual shapes and structures, and may include erectile tissue in various places all over the body or in strange locations.",
	"Extra Eyes": "This mutant has " + _.random(1, 6) + " more eyes than normal.",
	"Extra Fingers and Toes": "This mutant has " + _.random(1, 4) + "more fingers or toes than normal.",
	"Extra Joints": "This mutant has one or more extra joints in its limbs.",
	"Extra Orifices": "This mutant has and extra " + pick(orifices),
	"Extremely Thin": "This mutant can’t maintain a normal body weight for its species, and is very thin.",
	"Eyestalks": "This mutant’s eyes are on the end of stalks, which may or may not be semi-retractable.",
	"Fangs": "This mutant has dangerous " + pick(fangs),
	"Feathers": "This mutant has feathers on part or all of its body.",
	"Fin": "This mutant has a fin protruding from its back or head, which helps it swim.",
	"Flaking Skin": "This mutant has full-body dandruff due to dry and flaky skin.",
	"Flippers": "This mutant has flippers instead of either arms and hands, or both arms as well as legs.",
	"Fur": "This mutant has " + pick(fur) + " covering all or most of its body.",
	"Fused Ribs": "This mutant’s ribs are fused together, forming a bony plate across the upper torso.",
	"Gliding Membranes": "This mutant has membranes or flaps of skin between its limbs that, along with hollow bones, allows it to glide after jumping from heights.",
	"Hairless": "This mutant has no hair, fur, or feathers anywhere on its body.",
	"Headless": "This mutant has no head. Its face is located on its chest or some other part of its body.",
	"Hemihypertrophy": "One side of this mutant’s body is significantly larger than the other, resulting in an unattractive lack of symmetry. Limbs on one side are longer and stronger than those on the other side, and facial features are distorted.",
	"Hooks": "This mutant has hooks on its hands and/or feet, made of bone, cartilage, horn, or other material, that it can use as weapons, or to make climbing much easier.",
	"Hopper": "This mutant has one large, powerful leg that it hops around on. Maybe two legs.",
	"Horns": "This mutant has " + pick(horns) + " growing out of its head.",
	"Huge Beard": "This mutant has an enormous beard growing out of its face.",
	"Huge Head": "This mutant’s head is about twice as big as normal for its species.",
	"Hideous Appearance": "This mutant’s appearance is deformed in some way that makes it universally repugnant to others of its species.",
	"Hump": "This mutant has one or more humps on its back that store food and water, allowing the mutant to go without for extended periods of time.",
	"Hunchback": "This mutant’s back is twisted and hunched, making it slightly more difficult to move.",
	"Internal Weapon": "This mutant can produce a " + pick(weapon) + " from its own body, or transform part of its body into a weapon. The mutant can produce a single weapon, or one weapon per limb. These weapons can be hidden when not in use.",
	"Large Ears": "This mutant’s external ears are " + _.random(2, 11) + " times as large as normal for its species, or if its species does not have external ears, this mutant does. Because the ears direct sound, this can result in an increased ability to detect and identify specific noises.",
	"Large Rear End": "This mutant’s ass, hind quarters, or abdominal segment is extraordinarily large.",
	"Large Size": "This mutant is " + _.random(2, 4) + " times larger than normal for its species.",
	"Leaves": "This mutant is covered in " + pick(leaves) + ".",
	"Limb Loss": "This mutant has fewer limbs than is normal for its species. Missing a " + pick(limbs),
	"Limb Transference": "This mutant has an extra " + pick(limbs) + " on its " + pick(bodyLocation),
	"Long Face": "This mutant’s facial features are elongated to an extreme amount, giving it a long face.",
	"Long Legs": "This mutant’s legs are freakishly long, allowing it to move up to  per cent faster.",
	"Long Neck": "This mutant’s neck is at least d+ times as long as is normal for its species.",
	"Long Nose": "This mutant’s nose sticks out much farther than is considered extreme for its species.",
	"Long Tongue": "This mutant’s tongue is at least d+ times as long as is normal for its species.",
	"Loose Skin": "This mutant’s loose, baggy skin hangs off in folds and rolls, almost appearing to be melting.",
	"Mane": "This mutant’s head is framed by a " + pick(mane),
	"Mostly Hairless": "This mutant still has hair on the top of its head, but little or no hair on the rest of its body. It may or may not have eyebrows and/or a small patch of pubic hair, but cannot grow a beard.",
	"Multiple Arms": "This mutant has " + _.random(1, 4) + " more arm(s) than is normal for its species.",
	"Multiple Heads": "This mutant has " + _.random(1, 3) + " additional head(s).",
	"Multiple Legs": "This mutant has " + _.random(1, 4) + " more leg(s) than is normal for its species.",
	"No Ears": "This mutant has no " + pick(earlessness),
	"No Eyes": "This mutant has no eyes in its face.",
	"No Nose": "This mutant has slits for a nose instead of any external organ.",
	"No Skin": "This mutant has no skin protecting its fat, muscles, and internal organs from the environment. Either it has a hardy immune system or it uses some form of artificial skin.",
	"Oddly-Shaped Tongue": "This mutant’s tongue is not the normal shape for its species. It is a " + pick(tongue) + " tongue.",
	"One Eye": "This mutant has a single, cyclopean eye in the centre of its face.",
	"Overgrown Body Part": "This mutant's " + pick(bodyParts) + " have grown to " + _.random(2, 4) + " times larger than normal.",
	"Patterned Skin": "This mutant’s skin (or fur) is a " + pick(pattern) + " that is otherwise natural to the mutant’s species.",
	"Physically Immature": "This mutant looks like a child, and will always appear pre-pubescent no matter how old.",
	"Pinhead": "This mutant has a shrunken, tiny head. This affects brain size and mental capacities.",
	"Pointed Head": "This mutant has a pointed, cone-shaped head.",
	"Pouch": "This mutant has a pouch of skin, like a marsupial, or a similar compartment in its body.",
	"Protective Eyelids": "This mutant has additional, protective eyelids made of chitin, bone, or other material more durable than the mutant’s skin. They protect the mutant’s eyes from harm.",
	"Puny": "This mutant is shrivelled and weak, its muscles wasted and withered and its body as small as one-half normal size. The mutant’s physical capabilities are reduced by at least one quarter.",
	"Quills, Spines, or Thorns": "This mutant’s back (or other area) is covered in spiny quills that provide protection and can be used as weapons. There is a  in  chance the mutant will be able to project these quills, spines, or thorns d times each week before they must be regrown.",
	"Radula": "Instead of a tongue, this mutant has a toothed, chitinous ribbon like the radula of a mollusc, which can be used to scrape and cut food. It is still capable of speech.",
	"Re-Arranged Face": "This mutant’s face is completely re-arranged. Even though it still has all the normal facial features, they are all in completely different locations than is normal.",
	"Redundant Vital Organs": "This mutant has multiple " + pick(organs) + ", so that if one is damaged, the mutant is less aversely affected.",
	"Reverse Pedalism": "If the mutant is normally bipedal, it becomes a quadruped. If the mutant is normally quadrupedal, it becomes a biped. If the mutant has a different form of locomotion, reverse the limbs normally used for movement and manipulation.",
	"Scales": "This mutant’s skin is covered with scales.",
	"Scars": "This mutant bears prominent scars as a result of an over-production of scar tissue, a skin disease, or treatment of some other condition.",
	"Short Legs": "This mutant’s legs are abnormally short, cutting its normal movement rate and jumping distance by at least half.",
	"Siamese Twin": "This mutant has two bodies joined together at birth, which may or may not be two different people. Other mutations and powers may belong to both or either twin.",
	"Skull Face": "This mutant’s face resembles a skull, with either no skin on it, or only a small amount of skin that does not prevent the skull from showing through.",
	"Small Size": "This mutant is a miniature version of its normal race. " + _.random(2, 4) + " times smaller than usual.",
	"Snout": "This mutant has an elongated, snout-like face.",
	"Stomach Orifice": "This mutant has an extra orifice near its stomach that can consume and regurgitate food.",
	"Strange Ears": "This mutant has odd-looking ears.",
	"Strange Interior Organs": "The inside of this mutant’s body is completely different from that of others of its species, and its internal organs make no sense according to its exterior appearance.",
	"Strange Texture": "This mutant’s skin feels like " + pick(texture) + ".",
	"Strangely Coloured Eyes": "This mutant’s eyes are " + pick(colours) + ", and may not even have a visible iris or pupil.",
	"Strangely Coloured Hair": "This mutant’s hair is " + pick(colours) + ".",
	"Strangely Coloured Skin": "This mutant has skin that is " + pick(pattern) + " and " + pick(colours) + ".",
	"Stubby Digits": "This mutant has short and stubby fingers and toes.",
	"Sympathetic Biomorphism": "The physical form of this mutant changes to comply with the individuals it associates with, even if that shape has more limbs and sense organs. After " + pick(duration) + ", depending on speed, its will resemble those around it in shape, though its cosmetic appearance will not change.",
	"Tail": "This mutant has a " + pick(tail) + ".",
	"Taller": "This mutant is " + _.random(10, 100) + "% taller than the normal maximum height for its species. The mutant’s other dimensions are not proportionally filled out.",
	"Tentacles": "This mutant has " + pick(tentacles) + ".",
	"Tongueless": "This mutant has no tongue.",
	"Toothed Skin": "This mutant’s skin is covered in small scales that resemble sharp teeth, which can be used to cut and saw, and make it uncomfortable—even dangerous—for others to touch the mutant.",
	"Transparent Eyelids": "This mutant’s eyes have an additional pair of transparent eyelids, such as nictating membranes, that protect the eyes from damage without unduly impairing vision. These eyelids can be tinted, to aid vision in bright light, or designed to filter out certain colours.",
	"Trunk": "This mutant has a prehensile nose, like the trunk of an elephant.",
	"Tumours": "This mutant suffers from large tumours that grow on its body.",
	"Twisted Frame": "This mutant’s body shape is twisted and bent, making normal movements and posture difficult or even impossible. This reduces agility, co-ordination, and reflexes by half.",
	"Vestigial Wings": "A small, useless pair of wings sprouts from this mutant’s back or shoulders.",
	"Walking Head": "This mutant has no appreciable torso between its head and limbs and so appears to be a walking head.",
	"Warty Skin": "This mutant’s skin is covered in warty growths.",
	"Weapon Hands": "This mutant has hands formed in the shape of " + pick(weapons) + " weapons.",
	"Webbed Digits": "This mutant’s hands and feet are webbed, allowing it to swim faster.",
	"Whiskers": "This mutant has long whiskers on its face that it uses to aid perception.",
	"Wide": "This mutant is " + _.random(10, 100) + "% per cent wider than others of its species, but is normal-sized in all other respects.",
	"Wings": "If this mutant is already armless, it has " + pick(wings) + " in addition to any other limbs.",
	"Wrinkled Skin": "This mutant’s skin is covered in thick, pruny wrinkles, lines, and creases.",








};

//randomly chooses from a table, taking an optional lower limit value other than 1
function pick(table, lowerLimit) {
	var selection = '';
	var lastRange = _.last(table);
	var firstRange = _.first(table);
	var ceiling = _.last(lastRange.range);
	var floor = _.first(firstRange.range);;

	//option to set a floor other than 1
	if (typeof lowerLimit !== 'undefined') {
		floor = lowerLimit;
	}

	var random = _.random(floor, ceiling);

	//iterate through table object and checking random number in each range array, returning the key if true
	_.forEach(table, function(data) {
		var start = _.first(data.range);
		var end = _.last(data.range) + 1;
		var bool = _.inRange(random, start, end);

		if (bool == true) {
			selection = _.toLower(data.name);
			
			if (data.subtable !== undefined) {				
				selection = pick(data.subtable);
			}			
		}		
	});

	return selection;
}

var mutate = pick(mutationTableIndex);
mutate = "strangely coloured eyes";

//console.log(describe['Tentacles']);
//console.log(pick(armour));
var melody = pick(bodyForm);
console.log(melody);
mutate = _.startCase(melody);
console.log(describe[mutate]);


